In [2]:
import os

BASE = "/kaggle/input"

for root, dirs, files in os.walk(BASE):
    level = root.replace(BASE, "").count(os.sep)

    if level <= 2:
        print(root)
        for file in files[:10]:
            print("   ", file)

/kaggle/input
/kaggle/input/competitions
/kaggle/input/competitions/vinbigdata-chest-xray-abnormalities-detection
    sample_submission.csv
    train.csv
/kaggle/input/datasets
/kaggle/input/datasets/raddar

In [3]:
import os

print("INPUT DIRECTORIES:")
for item in os.listdir("/kaggle/input"):
    print(" -", item)

INPUT DIRECTORIES:
 - competitions
 - datasets

In [4]:
import os

BASE = "/kaggle/input/competitions"

for root, dirs, files in os.walk(BASE):
    level = root.replace(BASE, "").count(os.sep)

    if level <= 3:
        print(root)
        for file in files[:15]:
            print("   ", file)

/kaggle/input/competitions
/kaggle/input/competitions/vinbigdata-chest-xray-abnormalities-detection
    sample_submission.csv
    train.csv
/kaggle/input/competitions/vinbigdata-chest-xray-abnormalities-detection/test
    83caa8a85e03606cf57e49147d7ac569.dicom
    7550347fa2bb96c2354a3716dfa3a69c.dicom
    74b23792db329cff5843e36efb8aa65a.dicom
    94568a546be103177cb582d3e91cd2d8.dicom
    6da36354fc904b63bc03eb3884e0c35c.dicom
    5b3620a56668010877cfafa9322e18b5.dicom
    5157d5c9b1f0004b29310652ea54e825.dicom
    74897408dcbd69ef7c76cbbbbeb722d6.dicom
    271290de7e7e4fb8aa1c31327f48f4b5.dicom
    cdb9c0046cc8f9e32fcafc5517000525.dicom
    eb4c1f7a8fcd7ee076ae9f5eca8d05fc.dicom
    366fb4e84d6940ea74267b32edbd1311.dicom
    f5f77203f00504c40b45a65d23cd8948.dicom
    212dc39b6ba6941b034c2cd92cf97a8d.dicom
    a5eabc3dd2734b211c9b09205443a2ea.dicom
/kaggle/input/competitions/vinbigdata-chest-xray-abnormalities-detection/train
    4d390e07733ba06e5ff07412f09c0a92.dicom
    289f69f6462af4933308c275d07060f0.dicom
    68335ee73e67706aa59b8b55b54b11a4.dicom
    7ecd6f67f649f26c05805c8359f9e528.dicom
    2229148faa205e881cf0d932755c9e40.dicom
    8c87779485ae5e21e25cb57e9510e149.dicom
    76b23891649862f2b3b95f9bebf0a70c.dicom
    ba1795ee5daae1ed415756c3f4f21b48.dicom
    aa6475267e83947ee5078281a7ff3df3.dicom
    051c2436c0acdb5e09d085c7e4a764f3.dicom
    98617a2bbd11c4afa7be664889cdd6de.dicom
    f9ce61e625356d31cf67c8ce97186d22.dicom
    e6e1f33532a2f3f93d17d2be963cd122.dicom
    5f9656fef011ff6876d88f8042a1ec7c.dicom
    3a76b6f5eca1dc2946a8de6fe7764dc9.dicom

In [5]:
import pandas as pd

DATA_DIR = "/kaggle/input/competitions/vinbigdata-chest-xray-abnormalities-detection"

train_csv = f"{DATA_DIR}/train.csv"

df = pd.read_csv(train_csv)

print("Dataset shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 10 rows:")
display(df.head(10))

Dataset shape: (67914, 8)

Columns:
['image_id', 'class_name', 'class_id', 'rad_id', 'x_min', 'y_min', 'x_max', 'y_max']

First 10 rows:

,image_id,class_name,class_id,rad_id,x_min,y_min,x_max,y_max
0,50a418190bc3fb1ef1633bf9678929b3,No finding,14,R11,NaN,NaN,NaN,NaN
1,21a10246a5ec7af151081d0cd6d65dc9,No finding,14,R7,NaN,NaN,NaN,NaN
2,9a5094b2563a1ef3ff50dc5c7ff71345,Cardiomegaly,3,R10,691.0,1375.0,1653.0,1831.0
3,051132a778e61a86eb147c7c6f564dfe,Aortic enlargement,0,R10,1264.0,743.0,1611.0,1019.0
4,063319de25ce7edb9b1c6b8881290140,No finding,14,R10,NaN,NaN,NaN,NaN
5,1c32170b4af4ce1a3030eb8167753b06,Pleural thickening,11,R9,627.0,357.0,947.0,433.0
6,0c7a38f293d5f5e4846aa4ca6db4daf1,ILD,5,R17,1347.0,245.0,2188.0,2169.0
7,47ed17dcb2cbeec15182ed335a8b5a9e,Nodule/Mass,8,R9,557.0,2352.0,675.0,2484.0
8,d3637a1935a905b3c326af31389cb846,Aortic enlargement,0,R10,1329.0,743.0,1521.0,958.0
9,afb6230703512afc370f236e8fe98806,Pulmonary fibrosis,13,R9,1857.0,1607.0,2126.0,2036.0

In [6]:
print("Unique classes:")
print(df["class_name"].unique())

print("\nClass counts:")
display(
    df["class_name"]
    .value_counts()
    .rename_axis("class_name")
    .reset_index(name="count")
)

Unique classes:
['No finding' 'Cardiomegaly' 'Aortic enlargement' 'Pleural thickening'
 'ILD' 'Nodule/Mass' 'Pulmonary fibrosis' 'Lung Opacity' 'Atelectasis'
 'Other lesion' 'Infiltration' 'Pleural effusion' 'Calcification'
 'Consolidation' 'Pneumothorax']

Class counts:

            class_name  count
0           No finding  31818
1   Aortic enlargement   7162
2         Cardiomegaly   5427
3   Pleural thickening   4842
4   Pulmonary fibrosis   4655
5          Nodule/Mass   2580
6         Lung Opacity   2483
7     Pleural effusion   2476
8         Other lesion   2203
9         Infiltration   1247
10                 ILD   1000
11       Calcification    960
12       Consolidation    556
13         Atelectasis    279
14        Pneumothorax    226

In [7]:
print("Unique classes:")
print(df["class_name"].unique())

print("\nClass counts:")
class_counts = (
    df["class_name"]
    .value_counts()
    .rename_axis("class_name")
    .reset_index(name="count")
)

display(class_counts)

Unique classes:
['No finding' 'Cardiomegaly' 'Aortic enlargement' 'Pleural thickening'
 'ILD' 'Nodule/Mass' 'Pulmonary fibrosis' 'Lung Opacity' 'Atelectasis'
 'Other lesion' 'Infiltration' 'Pleural effusion' 'Calcification'
 'Consolidation' 'Pneumothorax']

Class counts:

            class_name  count
0           No finding  31818
1   Aortic enlargement   7162
2         Cardiomegaly   5427
3   Pleural thickening   4842
4   Pulmonary fibrosis   4655
5          Nodule/Mass   2580
6         Lung Opacity   2483
7     Pleural effusion   2476
8         Other lesion   2203
9         Infiltration   1247
10                 ILD   1000
11       Calcification    960
12       Consolidation    556
13         Atelectasis    279
14        Pneumothorax    226

In [8]:
print("Missing values:")
display(df.isnull().sum())

Missing values:

image_id          0
class_name        0
class_id          0
rad_id            0
x_min         31818
y_min         31818
x_max         31818
y_max         31818
dtype: int64

In [9]:
print("Number of unique images:", df["image_id"].nunique())
print("Number of annotation rows:", len(df))

print("\nAnnotations per image:")
annotations_per_image = df.groupby("image_id").size()

display(annotations_per_image.describe())

print("\nRadiologists:")
print("Unique radiologists:", df["rad_id"].nunique())
print(df["rad_id"].value_counts().sort_index())

Number of unique images: 15000
Number of annotation rows: 67914

Annotations per image:

count    15000.000000
mean         4.527600
std          3.582638
min          3.000000
25%          3.000000
50%          3.000000
75%          4.000000
max         57.000000
dtype: float64

Radiologists:
Unique radiologists: 17
rad_id
R1      1995
R10    13292
R11     1670
R12     1729
R13     1824
R14     1624
R15     1823
R16     1763
R17      812
R2      3121
R3      2285
R4      1513
R5      2783
R6      2041
R7      1733
R8     12198
R9     15708
Name: count, dtype: int64

In [10]:
print("Radiologists per image:")

radiologists_per_image = df.groupby("image_id")["rad_id"].nunique()

display(radiologists_per_image.describe())

print("\nDistribution:")
display(
    radiologists_per_image
    .value_counts()
    .sort_index()
    .rename_axis("number_of_radiologists")
    .reset_index(name="number_of_images")
)

Radiologists per image:

count    15000.0
mean         3.0
std          0.0
min          3.0
25%          3.0
50%          3.0
75%          3.0
max          3.0
Name: rad_id, dtype: float64

Distribution:

   number_of_radiologists  number_of_images
0                       3             15000

In [11]:
print("Radiologists per image:")

radiologists_per_image = df.groupby("image_id")["rad_id"].nunique()

display(radiologists_per_image.describe())

print("\nDistribution:")
display(
    radiologists_per_image
    .value_counts()
    .sort_index()
    .rename_axis("number_of_radiologists")
    .reset_index(name="number_of_images")
)

Radiologists per image:

count    15000.0
mean         3.0
std          0.0
min          3.0
25%          3.0
50%          3.0
75%          3.0
max          3.0
Name: rad_id, dtype: float64

Distribution:

   number_of_radiologists  number_of_images
0                       3             15000

In [12]:
# How many different radiologists labeled each class?
agreement = (
    df.groupby(["image_id", "class_name"])["rad_id"]
      .nunique()
      .reset_index(name="radiologist_count")
)

print("Radiologist agreement for Nodule/Mass:")
display(
    agreement[agreement["class_name"] == "Nodule/Mass"]
    .describe()
)

Radiologist agreement for Nodule/Mass:

       radiologist_count
count         826.000000
mean            1.709443
std             0.803226
min             1.000000
25%             1.000000
50%             1.000000
75%             2.000000
max             3.000000

In [13]:
print("Nodule/Mass examples with multiple radiologists:")

nodule_agreement = agreement[
    agreement["class_name"] == "Nodule/Mass"
].sort_values("radiologist_count", ascending=False)

display(nodule_agreement.head(20))

Nodule/Mass examples with multiple radiologists:

                               image_id   class_name  radiologist_count
186    01a3c3d994d85ce5634d2d13c03fd4b0  Nodule/Mass                  3
25899  ff0191df898268978f2c29231450fd66  Nodule/Mass                  3
12410  7bd856b30b7129c81c6803c7f1fe23b3  Nodule/Mass                  3
12463  7c5f3e2c0518bba6ca3464c385d4787c  Nodule/Mass                  3
12576  7d48ee923365d79f033147cd5f4aafc1  Nodule/Mass                  3
12603  7d746268923b15615c93334eff3a6baf  Nodule/Mass                  3
12688  7e534f2dc65f7cef4f864325433017dd  Nodule/Mass                  3
13090  81e1bdd75db3ed8260cd2a8a206107a4  Nodule/Mass                  3
13691  879caa633ff0c3c5a9f2c483e757b991  Nodule/Mass                  3
24645  f24f5cb1232f59b8688e655a48127b43  Nodule/Mass                  3
24830  f40c08b38fce6f2b77c6019d34521357  Nodule/Mass                  3
1228   0c31081e8ada2990bcbef0f12ea60b07  Nodule/Mass                  3
1248   0c5ff01c7bfb4362fcd98f36e555b08c  Nodule/Mass                  3
1330   0d03df2e9ed557d0c9edcec777056c1f  Nodule/Mass                  3
582    059ec0fc0d6840cff6e268e46f85faa0  Nodule/Mass                  3
13696  87a516c6446958f3f56cf3e4ab8a0c5f  Nodule/Mass                  3
13732  87f7997c901c0026e338e6f6d79b385f  Nodule/Mass                  3
13768  8862ef75274d0c13bba19d7b5f2147c6  Nodule/Mass                  3
13798  88bf02cc510da5050a869c290d8f8565  Nodule/Mass                  3
11612  735023a2b17a5222636abc2784772804  Nodule/Mass                  3

In [14]:
# Nodule/Mass agreement across the 3 radiologists

nodule = df[df["class_name"] == "Nodule/Mass"].copy()

nodule_by_image = (
    nodule.groupby("image_id")["rad_id"]
    .nunique()
    .value_counts()
    .sort_index()
)

print("Number of radiologists identifying Nodule/Mass:")
display(
    nodule_by_image
    .rename_axis("radiologists_identifying_nodule_mass")
    .reset_index(name="number_of_images")
)

Number of radiologists identifying Nodule/Mass:

   radiologists_identifying_nodule_mass  number_of_images
0                                     1               421
1                                     2               224
2                                     3               181

In [15]:
# Show examples where multiple radiologists identified Nodule/Mass

nodule_agreement = (
    nodule.groupby("image_id")
    .agg(
        radiologist_count=("rad_id", "nunique"),
        radiologists=("rad_id", lambda x: ", ".join(sorted(x.unique())))
    )
    .reset_index()
    .sort_values("radiologist_count", ascending=False)
)

print("Examples of Nodule/Mass agreement:")
display(nodule_agreement.head(20))

Examples of Nodule/Mass agreement:

                             image_id  radiologist_count   radiologists
7    01a3c3d994d85ce5634d2d13c03fd4b0                  3    R10, R8, R9
824  ff0191df898268978f2c29231450fd66                  3    R10, R8, R9
391  7bd856b30b7129c81c6803c7f1fe23b3                  3    R10, R8, R9
392  7c5f3e2c0518bba6ca3464c385d4787c                  3    R10, R8, R9
399  7d48ee923365d79f033147cd5f4aafc1                  3    R10, R8, R9
401  7d746268923b15615c93334eff3a6baf                  3  R12, R13, R15
404  7e534f2dc65f7cef4f864325433017dd                  3    R10, R8, R9
412  81e1bdd75db3ed8260cd2a8a206107a4                  3    R10, R8, R9
427  879caa633ff0c3c5a9f2c483e757b991                  3    R10, R8, R9
778  f24f5cb1232f59b8688e655a48127b43                  3    R10, R8, R9
785  f40c08b38fce6f2b77c6019d34521357                  3    R10, R8, R9
43   0c31081e8ada2990bcbef0f12ea60b07                  3    R10, R8, R9
44   0c5ff01c7bfb4362fcd98f36e555b08c                  3    R10, R8, R9
46   0d03df2e9ed557d0c9edcec777056c1f                  3    R10, R8, R9
24   059ec0fc0d6840cff6e268e46f85faa0                  3  R13, R14, R15
428  87a516c6446958f3f56cf3e4ab8a0c5f                  3    R10, R8, R9
429  87f7997c901c0026e338e6f6d79b385f                  3  R14, R15, R16
431  8862ef75274d0c13bba19d7b5f2147c6                  3    R10, R8, R9
433  88bf02cc510da5050a869c290d8f8565                  3    R10, R8, R9
374  735023a2b17a5222636abc2784772804                  3    R10, R8, R9

In [16]:
# Inspect all annotations for a few images with Nodule/Mass

example_ids = nodule_agreement.head(5)["image_id"].tolist()

display(
    df[df["image_id"].isin(example_ids)]
    .sort_values(["image_id", "rad_id"])
)

,image_id,class_name,class_id,rad_id,x_min,y_min,x_max,y_max
50820,01a3c3d994d85ce5634d2d13c03fd4b0,Nodule/Mass,8,R10,812.0,1001.0,1189.0,1292.0
58913,01a3c3d994d85ce5634d2d13c03fd4b0,Consolidation,4,R10,812.0,1001.0,1189.0,1292.0
63964,01a3c3d994d85ce5634d2d13c03fd4b0,Lung Opacity,7,R10,812.0,1001.0,1189.0,1292.0
67595,01a3c3d994d85ce5634d2d13c03fd4b0,Pleural effusion,10,R10,705.0,1492.0,1327.0,2084.0
34918,01a3c3d994d85ce5634d2d13c03fd4b0,Nodule/Mass,8,R8,860.0,996.0,1162.0,1309.0
41552,01a3c3d994d85ce5634d2d13c03fd4b0,Pleural thickening,11,R8,1038.0,314.0,1456.0,606.0
47329,01a3c3d994d85ce5634d2d13c03fd4b0,Pleural thickening,11,R8,671.0,1460.0,1063.0,1826.0
50070,01a3c3d994d85ce5634d2d13c03fd4b0,Pleural thickening,11,R8,688.0,314.0,1031.0,1453.0
65595,01a3c3d994d85ce5634d2d13c03fd4b0,Lung Opacity,7,R8,787.0,1289.0,1339.0,1672.0
26254,01a3c3d994d85ce5634d2d13c03fd4b0,Nodule/Mass,8,R9,844.0,1018.0,1179.0,1309.0
45002,01a3c3d994d85ce5634d2d13c03fd4b0,Consolidation,4,R9,844.0,1018.0,1179.0,1309.0
48077,01a3c3d994d85ce5634d2d13c03fd4b0,Lung Opacity,7,R9,756.0,978.0,1378.0,1691.0
51210,01a3c3d994d85ce5634d2d13c03fd4b0,Pleural thickening,11,R9,830.0,308.0,1418.0,915.0
66173,01a3c3d994d85ce5634d2d13c03fd4b0,Pleural effusion,10,R9,660.0,1548.0,1378.0,1878.0
707,7bd856b30b7129c81c6803c7f1fe23b3,Other lesion,9,R10,932.0,1333.0,1274.0,1763.0
1115,7bd856b30b7129c81c6803c7f1fe23b3,Pleural thickening,11,R10,2324.0,1748.0,2539.0,2014.0
5944,7bd856b30b7129c81c6803c7f1fe23b3,Nodule/Mass,8,R10,932.0,1333.0,1274.0,1763.0
53808,7bd856b30b7129c81c6803c7f1fe23b3,Pleural effusion,10,R10,2324.0,1748.0,2539.0,2014.0
67448,7bd856b30b7129c81c6803c7f1fe23b3,Cardiomegaly,3,R10,989.0,1514.0,2206.0,1982.0
21705,7bd856b30b7129c81c6803c7f1fe23b3,Pleural effusion,10,R8,2264.0,1709.0,2542.0,1970.0
58191,7bd856b30b7129c81c6803c7f1fe23b3,Cardiomegaly,3,R8,1004.0,1474.0,2237.0,1970.0
61660,7bd856b30b7129c81c6803c7f1fe23b3,Nodule/Mass,8,R8,925.0,1352.0,1308.0,1765.0
5593,7bd856b30b7129c81c6803c7f1fe23b3,Nodule/Mass,8,R9,906.0,1297.0,1278.0,1775.0
35009,7bd856b30b7129c81c6803c7f1fe23b3,Cardiomegaly,3,R9,962.0,1719.0,2250.0,2101.0
47919,7bd856b30b7129c81c6803c7f1fe23b3,Aortic enlargement,0,R9,1444.0,782.0,1773.0,1118.0
51900,7bd856b30b7129c81c6803c7f1fe23b3,Pleural effusion,10,R9,2289.0,1684.0,2573.0,2217.0
34752,7c5f3e2c0518bba6ca3464c385d4787c,Aortic enlargement,0,R10,1421.0,1157.0,1853.0,1776.0
42329,7c5f3e2c0518bba6ca3464c385d4787c,Pulmonary fibrosis,13,R10,2243.0,2205.0,2405.0,2364.0
53063,7c5f3e2c0518bba6ca3464c385d4787c,Consolidation,4,R10,1368.0,807.0,2023.0,1603.0
60153,7c5f3e2c0518bba6ca3464c385d4787c,Cardiomegaly,3,R10,972.0,2243.0,2228.0,2704.0
60490,7c5f3e2c0518bba6ca3464c385d4787c,Nodule/Mass,8,R10,1368.0,807.0,2023.0,1603.0
42886,7c5f3e2c0518bba6ca3464c385d4787c,Nodule/Mass,8,R8,1406.0,885.0,2025.0,1660.0
44691,7c5f3e2c0518bba6ca3464c385d4787c,Aortic enlargement,0,R8,1452.0,1153.0,1873.0,1741.0
57752,7c5f3e2c0518bba6ca3464c385d4787c,Pulmonary fibrosis,13,R8,2249.0,2181.0,2424.0,2338.0
2758,7c5f3e2c0518bba6ca3464c385d4787c,Nodule/Mass,8,R9,1521.0,876.0,2028.0,1579.0
6341,7c5f3e2c0518bba6ca3464c385d4787c,Pulmonary fibrosis,13,R9,2260.0,2187.0,2396.0,2347.0
24604,7c5f3e2c0518bba6ca3464c385d4787c,Pleural effusion,10,R9,2374.0,2290.0,2513.0,2504.0
36380,7c5f3e2c0518bba6ca3464c385d4787c,Aortic enlargement,0,R9,1293.0,1161.0,1854.0,1838.0
56826,7c5f3e2c0518bba6ca3464c385d4787c,Pleural thickening,11,R9,2374.0,2290.0,2513.0,2504.0
64640,7c5f3e2c0518bba6ca3464c385d4787c,Other lesion,9,R9,2260.0,2187.0,2396.0,2347.0
22659,7d48ee923365d79f033147cd5f4aafc1,Nodule/Mass,8,R10,1381.0,1462.0,1471.0,1568.0
54820,7d48ee923365d79f033147cd5f4aafc1,Nodule/Mass,8,R10,559.0,1467.0,670.0,1565.0
34027,7d48ee923365d79f033147cd5f4aafc1,Nodule/Mass,8,R8,1378.0,1456.0,1468.0,1566.0
59531,7d48ee923365d79f033147cd5f4aafc1,Nodule/Mass,8,R8,567.0,1467.0,654.0,1557.0
7492,7d48ee923365d79f033147cd5f4aafc1,Nodule/Mass,8,R9,549.0,1460.0,668.0,1565.0
65170,7d48ee923365d79f033147cd5f4aafc1,Nodule/Mass,8,R9,1369.0,1453.0,1467.0,1567.0
55317,ff0191df898268978f2c29231450fd66,Nodule/Mass,8,R10,2109.0,904.0,2226.0,991.0
2071,ff0191df898268978f2c29231450fd66,Nodule/Mass,8,R8,2104.0,899.0,2225.0,994.0
37591,ff0191df898268978f2c29231450fd66,Pulmonary fibrosis,13,R8,2157.0,860.0,2416.0,973.0
10454,ff0191df898268978f2c29231450fd66,Pulmonary fibrosis,13,R9,2079.0,869.0,2244.0,991.0
43637,ff0191df898268978f2c29231450fd66,Nodule/Mass,8,R9,2079.0,869.0,2244.0,991.0

In [17]:
nodule = df[df["class_name"] == "Nodule/Mass"].copy()

print("Nodule/Mass annotation rows:", len(nodule))
print("Unique Nodule/Mass images:", nodule["image_id"].nunique())

display(
    nodule[
        [
            "image_id",
            "rad_id",
            "x_min",
            "y_min",
            "x_max",
            "y_max"
        ]
    ].head(20)
)

Nodule/Mass annotation rows: 2580
Unique Nodule/Mass images: 826

                             image_id rad_id   x_min   y_min   x_max   y_max
7    47ed17dcb2cbeec15182ed335a8b5a9e     R9   557.0  2352.0   675.0  2484.0
40   8e063eadea9a6aeb684c893c8598be3e    R10   376.0  1867.0   438.0  1914.0
56   d106ec9b305178f3da060efe3191499a     R8   796.0  1078.0   850.0  1129.0
59   f32ab457c492c30221d3a89fe7c6b25a    R15  1202.0  1090.0  1590.0  1654.0
66   a3f5ac68c8d1b1805be21f18c47fc186     R9  2123.0   922.0  2233.0  1010.0
76   9598f874069cca35ff56d54925d35ccb    R10  1468.0  1616.0  1698.0  1812.0
82   d07557904cbe57fc1bdebac1e8aeefa1     R9   378.0   899.0   403.0   929.0
118  604340ab6423f81a91ac72182163e9a4     R9  1661.0   568.0  1766.0   701.0
173  2ad18a594cbaf3c6d6145a7775829554    R10  2243.0  1742.0  2290.0  1797.0
174  15c3fc505c414c69ba757cb3be3ed213     R8   713.0  1634.0   791.0  1695.0
203  cca122e46a24a6ccfeba9ade9f7b933c     R8  1577.0  1890.0  1642.0  1956.0
237  3a302fbbbf3364aa1a7731b59e6b98ec     R9   237.0  1128.0   718.0  1727.0
288  53b1a490cd7e3a30e94014bdfd314d14     R9  1625.0   649.0  1714.0   757.0
362  2dd5e1ec060f1389e24a4caffa6d534e     R9  2152.0  2098.0  2182.0  2137.0
444  e694841193437bcb89ad2c1acbf95f79     R8  1594.0  1222.0  1743.0  1381.0
496  e31be972e181987a8600a8700c1ebe88    R10  1959.0   492.0  2030.0   663.0
523  edb61d8f85f46f6da703ab9730bf35b1    R10   972.0  1199.0  1047.0  1272.0
524  d59d5dcc1601a29509f91dab5f8550bc    R10  1472.0   710.0  1501.0   728.0
571  c8634131ee43469be8f4f75ab4595b10    R10  1547.0  1640.0  1668.0  1719.0
576  53e93d9f8cf885a55e00079256595a86    R10   346.0  1901.0   464.0  1974.0

In [18]:
nodule["box_width"] = nodule["x_max"] - nodule["x_min"]
nodule["box_height"] = nodule["y_max"] - nodule["y_min"]
nodule["box_area"] = nodule["box_width"] * nodule["box_height"]

display(
    nodule[
        [
            "box_width",
            "box_height",
            "box_area"
        ]
    ].describe()
)

         box_width   box_height      box_area
count  2580.000000  2580.000000  2.580000e+03
mean    170.809690   200.051550  7.354635e+04
std     172.424323   254.828224  1.944603e+05
min      11.000000    12.000000  1.800000e+02
25%      61.000000    61.000000  3.660000e+03
50%     102.000000   100.000000  9.972500e+03
75%     218.250000   230.250000  5.323025e+04
max    2114.000000  2363.000000  4.179378e+06

In [19]:
import numpy as np
import pandas as pd

nodule = df[df["class_name"] == "Nodule/Mass"].copy()

def calculate_iou(box1, box2):
    x1_min, y1_min, x1_max, y1_max = box1
    x2_min, y2_min, x2_max, y2_max = box2

    inter_xmin = max(x1_min, x2_min)
    inter_ymin = max(y1_min, y2_min)
    inter_xmax = min(x1_max, x2_max)
    inter_ymax = min(y1_max, y2_max)

    inter_w = max(0, inter_xmax - inter_xmin)
    inter_h = max(0, inter_ymax - inter_ymin)
    intersection = inter_w * inter_h

    area1 = max(0, x1_max - x1_min) * max(0, y1_max - y1_min)
    area2 = max(0, x2_max - x2_min) * max(0, y2_max - y2_min)

    union = area1 + area2 - intersection

    if union == 0:
        return 0.0

    return intersection / union


# Calculate pairwise IoU within each image
ious = []

for image_id, group in nodule.groupby("image_id"):

    records = group[
        ["rad_id", "x_min", "y_min", "x_max", "y_max"]
    ].to_dict("records")

    for i in range(len(records)):
        for j in range(i + 1, len(records)):

            box1 = (
                records[i]["x_min"],
                records[i]["y_min"],
                records[i]["x_max"],
                records[i]["y_max"]
            )

            box2 = (
                records[j]["x_min"],
                records[j]["y_min"],
                records[j]["x_max"],
                records[j]["y_max"]
            )

            iou = calculate_iou(box1, box2)

            ious.append({
                "image_id": image_id,
                "rad1": records[i]["rad_id"],
                "rad2": records[j]["rad_id"],
                "iou": iou
            })

iou_df = pd.DataFrame(ious)

print("Number of Nodule/Mass annotation pairs:", len(iou_df))

print("\nIoU statistics:")
display(iou_df["iou"].describe())

Number of Nodule/Mass annotation pairs: 11309

IoU statistics:

count    11309.000000
mean         0.064751
std          0.205870
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max          0.958109
Name: iou, dtype: float64

In [20]:
print("\nIoU categories:")

iou_categories = pd.cut(
    iou_df["iou"],
    bins=[-0.001, 0, 0.25, 0.50, 0.75, 1.0],
    labels=[
        "No overlap",
        "Low overlap",
        "Moderate overlap",
        "High overlap",
        "Very high overlap"
    ]
)

display(
    iou_categories
    .value_counts()
    .sort_index()
    .rename_axis("IoU category")
    .reset_index(name="annotation_pairs")
)

IoU categories:

        IoU category  annotation_pairs
0         No overlap              9672
1        Low overlap               613
2   Moderate overlap               120
3       High overlap               449
4  Very high overlap               455

In [21]:
import os
import pydicom

TRAIN_DIR = (
    "/kaggle/input/competitions/"
    "vinbigdata-chest-xray-abnormalities-detection/train"
)

sample_files = [
    f for f in os.listdir(TRAIN_DIR)
    if f.endswith(".dicom")
][:10]

print("Sample DICOM files:", len(sample_files))

for filename in sample_files:
    path = os.path.join(TRAIN_DIR, filename)

    ds = pydicom.dcmread(path, stop_before_pixels=False)

    print("\nFile:", filename)
    print("Rows:", getattr(ds, "Rows", None))
    print("Columns:", getattr(ds, "Columns", None))
    print("Photometric Interpretation:",
          getattr(ds, "PhotometricInterpretation", None))
    print("Pixel Spacing:",
          getattr(ds, "PixelSpacing", None))

Sample DICOM files: 10

File: 4d390e07733ba06e5ff07412f09c0a92.dicom
Rows: 3000
Columns: 3000
Photometric Interpretation: MONOCHROME2
Pixel Spacing: None

File: 289f69f6462af4933308c275d07060f0.dicom
Rows: 3072
Columns: 3072
Photometric Interpretation: MONOCHROME2
Pixel Spacing: [0.140, 0.140]

File: 68335ee73e67706aa59b8b55b54b11a4.dicom
Rows: 2836
Columns: 2336
Photometric Interpretation: MONOCHROME1
Pixel Spacing: [0.15, 0.15]

File: 7ecd6f67f649f26c05805c8359f9e528.dicom
Rows: 2952
Columns: 2744
Photometric Interpretation: MONOCHROME2
Pixel Spacing: [0.127, 0.127]

File: 2229148faa205e881cf0d932755c9e40.dicom
Rows: 2880
Columns: 2304
Photometric Interpretation: MONOCHROME1
Pixel Spacing: [0.15, 0.15]

File: 8c87779485ae5e21e25cb57e9510e149.dicom
Rows: 3170
Columns: 2642
Photometric Interpretation: MONOCHROME2
Pixel Spacing: [0.125, 0.125]

File: 76b23891649862f2b3b95f9bebf0a70c.dicom
Rows: 2819
Columns: 2545
Photometric Interpretation: MONOCHROME2
Pixel Spacing: [0.125, 0.125]

File: ba1795ee5daae1ed415756c3f4f21b48.dicom
Rows: 3408
Columns: 3320
Photometric Interpretation: MONOCHROME2
Pixel Spacing: None

File: aa6475267e83947ee5078281a7ff3df3.dicom
Rows: 3408
Columns: 2597
Photometric Interpretation: MONOCHROME2
Pixel Spacing: [0.125, 0.125]

File: 051c2436c0acdb5e09d085c7e4a764f3.dicom
Rows: 2728
Columns: 2596
Photometric Interpretation: MONOCHROME2
Pixel Spacing: [0.127, 0.127]

In [25]:
# --------------------------------------------------
# RESTART-SAFE: Load annotations + image dimensions
# --------------------------------------------------

import os
import numpy as np
import pandas as pd
import pydicom

DATA_DIR = (
    "/kaggle/input/competitions/"
    "vinbigdata-chest-xray-abnormalities-detection"
)

TRAIN_DIR = os.path.join(DATA_DIR, "train")

# Always reload the original annotation CSV
df = pd.read_csv(
    os.path.join(DATA_DIR, "train.csv")
)

print("Original annotation table:", df.shape)

# --------------------------------------------------
# Read image dimensions
# --------------------------------------------------

image_dimensions = {}

dicom_files = [
    f for f in os.listdir(TRAIN_DIR)
    if f.endswith(".dicom")
]

print("DICOM files found:", len(dicom_files))

for filename in dicom_files:

    image_id = filename.replace(".dicom", "")
    path = os.path.join(TRAIN_DIR, filename)

    try:
        ds = pydicom.dcmread(
            path,
            stop_before_pixels=True
        )

        image_dimensions[image_id] = {
            "height": int(ds.Rows),
            "width": int(ds.Columns),
            "photometric": getattr(
                ds,
                "PhotometricInterpretation",
                None
            )
        }

    except Exception as e:
        print("Failed:", filename, e)

print(
    "Images with dimensions:",
    len(image_dimensions)
)

# --------------------------------------------------
# Convert dimensions to DataFrame
# --------------------------------------------------

dims = (
    pd.DataFrame.from_dict(
        image_dimensions,
        orient="index"
    )
    .rename_axis("image_id")
    .reset_index()
)

print("\nDimension table:")
display(dims.head())

# --------------------------------------------------
# Merge
# --------------------------------------------------

df = df.merge(
    dims,
    on="image_id",
    how="left",
    validate="many_to_one"
)

print("\nMerged dataset:", df.shape)

print("\nMissing image dimensions:")
print(
    df[
        ["height", "width", "photometric"]
    ].isnull().sum()
)

display(df.head())

Original annotation table: (67914, 8)
DICOM files found: 15000
Images with dimensions: 15000

Dimension table:

                           image_id  height  width  photometric
0  4d390e07733ba06e5ff07412f09c0a92    3000   3000  MONOCHROME2
1  289f69f6462af4933308c275d07060f0    3072   3072  MONOCHROME2
2  68335ee73e67706aa59b8b55b54b11a4    2836   2336  MONOCHROME1
3  7ecd6f67f649f26c05805c8359f9e528    2952   2744  MONOCHROME2
4  2229148faa205e881cf0d932755c9e40    2880   2304  MONOCHROME1

Merged dataset: (67914, 11)

Missing image dimensions:
height         0
width          0
photometric    0
dtype: int64

,image_id,class_name,class_id,rad_id,x_min,y_min,x_max,y_max,height,width,photometric
0,50a418190bc3fb1ef1633bf9678929b3,No finding,14,R11,NaN,NaN,NaN,NaN,2580,2332,MONOCHROME2
1,21a10246a5ec7af151081d0cd6d65dc9,No finding,14,R7,NaN,NaN,NaN,NaN,3159,2954,MONOCHROME2
2,9a5094b2563a1ef3ff50dc5c7ff71345,Cardiomegaly,3,R10,691.0,1375.0,1653.0,1831.0,2336,2080,MONOCHROME1
3,051132a778e61a86eb147c7c6f564dfe,Aortic enlargement,0,R10,1264.0,743.0,1611.0,1019.0,2880,2304,MONOCHROME1
4,063319de25ce7edb9b1c6b8881290140,No finding,14,R10,NaN,NaN,NaN,NaN,3072,2540,MONOCHROME2

In [26]:
# --------------------------------------------------
# CREATE NORMALIZED BOUNDING-BOX FEATURES
# --------------------------------------------------

bbox_mask = (
    df["x_min"].notna()
    & df["y_min"].notna()
    & df["x_max"].notna()
    & df["y_max"].notna()
)

df["box_width"] = np.where(
    bbox_mask,
    df["x_max"] - df["x_min"],
    np.nan
)

df["box_height"] = np.where(
    bbox_mask,
    df["y_max"] - df["y_min"],
    np.nan
)

df["box_area"] = (
    df["box_width"] *
    df["box_height"]
)

# Normalized dimensions
df["box_width_norm"] = (
    df["box_width"] / df["width"]
)

df["box_height_norm"] = (
    df["box_height"] / df["height"]
)

df["box_area_norm"] = (
    df["box_area"] /
    (df["width"] * df["height"])
)

# Normalized center coordinates
df["center_x_norm"] = (
    ((df["x_min"] + df["x_max"]) / 2)
    / df["width"]
)

df["center_y_norm"] = (
    ((df["y_min"] + df["y_max"]) / 2)
    / df["height"]
)

print("Bounding-box features created.")

display(
    df[
        [
            "image_id",
            "class_name",
            "box_width_norm",
            "box_height_norm",
            "box_area_norm",
            "center_x_norm",
            "center_y_norm"
        ]
    ].head(20)
)

Bounding-box features created.

,image_id,class_name,box_width_norm,box_height_norm,box_area_norm,center_x_norm,center_y_norm
0,50a418190bc3fb1ef1633bf9678929b3,No finding,NaN,NaN,NaN,NaN,NaN
1,21a10246a5ec7af151081d0cd6d65dc9,No finding,NaN,NaN,NaN,NaN,NaN
2,9a5094b2563a1ef3ff50dc5c7ff71345,Cardiomegaly,0.462500,0.195205,0.090283,0.563462,0.686216
3,051132a778e61a86eb147c7c6f564dfe,Aortic enlargement,0.150608,0.095833,0.014433,0.623915,0.305903
4,063319de25ce7edb9b1c6b8881290140,No finding,NaN,NaN,NaN,NaN,NaN
5,1c32170b4af4ce1a3030eb8167753b06,Pleural thickening,0.125984,0.024740,0.003117,0.309843,0.128581
6,0c7a38f293d5f5e4846aa4ca6db4daf1,ILD,0.368053,0.753033,0.277156,0.773523,0.472407
7,47ed17dcb2cbeec15182ed335a8b5a9e,Nodule/Mass,0.045950,0.039368,0.001809,0.239875,0.721145
8,d3637a1935a905b3c326af31389cb846,Aortic enlargement,0.083333,0.074653,0.006221,0.618490,0.295312
9,afb6230703512afc370f236e8fe98806,Pulmonary fibrosis,0.105906,0.139648,0.014790,0.784055,0.592936
10,7c1add6833d5f0102b0d3619a1682a64,Lung Opacity,0.102921,0.063371,0.006522,0.255265,0.473623
11,18a61a07e6f5f13ebfee57fa36cd8b6f,Pulmonary fibrosis,0.186198,0.125000,0.023275,0.263672,0.160764
12,5550a493b1c4554da469a072fdfab974,No finding,NaN,NaN,NaN,NaN,NaN
13,869f39afbdd8783b531530942eda8bad,No finding,NaN,NaN,NaN,NaN,NaN
14,321c111713c3ee5385db0effb54ff568,Aortic enlargement,0.080295,0.087153,0.006998,0.600911,0.235937
15,f55460fccf2d3c591f57f9c0de2c37c2,No finding,NaN,NaN,NaN,NaN,NaN
16,cdbacab6bf30170ef0ba9fd1d195d270,No finding,NaN,NaN,NaN,NaN,NaN
17,80caa435b6ab5edaff4a0a758ffaec6e,Atelectasis,0.350883,0.612488,0.214912,0.285738,0.454940
18,5da264775732004f1b724b660138854a,Aortic enlargement,0.111654,0.155599,0.017373,0.588053,0.296875
19,fb8e11c6b2886b2d41b379e0598669b9,Aortic enlargement,0.098090,0.098958,0.009707,0.652344,0.354340

In [27]:
# ============================================================
# CONAN IMAGING — STEP 2
# Load VinBigData annotations + DICOM image dimensions
# ============================================================

import os
import numpy as np
import pandas as pd
import pydicom

# ------------------------------------------------------------
# 1. Paths
# ------------------------------------------------------------

DATA_DIR = (
    "/kaggle/input/competitions/"
    "vinbigdata-chest-xray-abnormalities-detection"
)

TRAIN_DIR = os.path.join(DATA_DIR, "train")
CSV_PATH = os.path.join(DATA_DIR, "train.csv")

print("DATA DIRECTORY:")
print(DATA_DIR)

print("\nTRAIN DIRECTORY:")
print(TRAIN_DIR)

# ------------------------------------------------------------
# 2. Load original VinBigData annotations
# ------------------------------------------------------------

df = pd.read_csv(CSV_PATH)

print("\nOriginal annotation dataset:")
print("Rows:", len(df))
print("Columns:", len(df.columns))
print(df.columns.tolist())

# ------------------------------------------------------------
# 3. Find all DICOM files
# ------------------------------------------------------------

dicom_files = [
    f for f in os.listdir(TRAIN_DIR)
    if f.lower().endswith(".dicom")
]

print("\nDICOM files found:", len(dicom_files))

# ------------------------------------------------------------
# 4. Read image dimensions
# ------------------------------------------------------------

image_dimensions = {}

failed_files = []

for i, filename in enumerate(dicom_files):

    image_id = filename.rsplit(".", 1)[0]

    path = os.path.join(TRAIN_DIR, filename)

    try:

        ds = pydicom.dcmread(
            path,
            stop_before_pixels=True
        )

        image_dimensions[image_id] = {
            "height": int(ds.Rows),
            "width": int(ds.Columns),
            "photometric": getattr(
                ds,
                "PhotometricInterpretation",
                None
            )
        }

    except Exception as e:

        failed_files.append(
            (filename, str(e))
        )

# ------------------------------------------------------------
# 5. Create image-dimension table
# ------------------------------------------------------------

dims = pd.DataFrame(
    [
        {
            "image_id": image_id,
            "height": values["height"],
            "width": values["width"],
            "photometric": values["photometric"]
        }
        for image_id, values
        in image_dimensions.items()
    ]
)

print("\nImage dimension table:")
print("Rows:", len(dims))

display(dims.head())

# ------------------------------------------------------------
# 6. Check dimension reading
# ------------------------------------------------------------

print("\nFailed DICOM files:", len(failed_files))

if failed_files:
    display(
        pd.DataFrame(
            failed_files,
            columns=["filename", "error"]
        ).head()
    )

# ------------------------------------------------------------
# 7. Check duplicate image IDs
# ------------------------------------------------------------

print(
    "\nDuplicate image IDs in dimension table:",
    dims["image_id"].duplicated().sum()
)

# ------------------------------------------------------------
# 8. Merge annotations with dimensions
# ------------------------------------------------------------

df = df.merge(
    dims,
    on="image_id",
    how="left",
    validate="many_to_one"
)

print("\nMerged dataset:")
print("Rows:", len(df))
print("Columns:", len(df.columns))

print("\nColumns:")
print(df.columns.tolist())

# ------------------------------------------------------------
# 9. Verify missing dimensions
# ------------------------------------------------------------

print("\nMissing dimensions:")

display(
    df[
        ["height", "width", "photometric"]
    ].isnull().sum()
)

# ------------------------------------------------------------
# 10. Verify image coverage
# ------------------------------------------------------------

annotation_images = set(
    df["image_id"].unique()
)

dimension_images = set(
    dims["image_id"].unique()
)

print("\nUnique annotation images:",
      len(annotation_images))

print("Unique dimension images:",
      len(dimension_images))

print(
    "Annotation images without dimensions:",
    len(annotation_images - dimension_images)
)

# ------------------------------------------------------------
# 11. Final preview
# ------------------------------------------------------------

print("\nFinal preview:")

display(
    df[
        [
            "image_id",
            "class_name",
            "rad_id",
            "x_min",
            "y_min",
            "x_max",
            "y_max",
            "height",
            "width",
            "photometric"
        ]
    ].head(10)
)

DATA DIRECTORY:
/kaggle/input/competitions/vinbigdata-chest-xray-abnormalities-detection

TRAIN DIRECTORY:
/kaggle/input/competitions/vinbigdata-chest-xray-abnormalities-detection/train

Original annotation dataset:
Rows: 67914
Columns: 8
['image_id', 'class_name', 'class_id', 'rad_id', 'x_min', 'y_min', 'x_max', 'y_max']

DICOM files found: 15000

Image dimension table:
Rows: 15000

                           image_id  height  width  photometric
0  4d390e07733ba06e5ff07412f09c0a92    3000   3000  MONOCHROME2
1  289f69f6462af4933308c275d07060f0    3072   3072  MONOCHROME2
2  68335ee73e67706aa59b8b55b54b11a4    2836   2336  MONOCHROME1
3  7ecd6f67f649f26c05805c8359f9e528    2952   2744  MONOCHROME2
4  2229148faa205e881cf0d932755c9e40    2880   2304  MONOCHROME1

Failed DICOM files: 0

Duplicate image IDs in dimension table: 0

Merged dataset:
Rows: 67914
Columns: 11

Columns:
['image_id', 'class_name', 'class_id', 'rad_id', 'x_min', 'y_min', 'x_max', 'y_max', 'height', 'width', 'photometric']

Missing dimensions:

height         0
width          0
photometric    0
dtype: int64

Unique annotation images: 15000
Unique dimension images: 15000
Annotation images without dimensions: 0

Final preview:

,image_id,class_name,rad_id,x_min,y_min,x_max,y_max,height,width,photometric
0,50a418190bc3fb1ef1633bf9678929b3,No finding,R11,NaN,NaN,NaN,NaN,2580,2332,MONOCHROME2
1,21a10246a5ec7af151081d0cd6d65dc9,No finding,R7,NaN,NaN,NaN,NaN,3159,2954,MONOCHROME2
2,9a5094b2563a1ef3ff50dc5c7ff71345,Cardiomegaly,R10,691.0,1375.0,1653.0,1831.0,2336,2080,MONOCHROME1
3,051132a778e61a86eb147c7c6f564dfe,Aortic enlargement,R10,1264.0,743.0,1611.0,1019.0,2880,2304,MONOCHROME1
4,063319de25ce7edb9b1c6b8881290140,No finding,R10,NaN,NaN,NaN,NaN,3072,2540,MONOCHROME2
5,1c32170b4af4ce1a3030eb8167753b06,Pleural thickening,R9,627.0,357.0,947.0,433.0,3072,2540,MONOCHROME2
6,0c7a38f293d5f5e4846aa4ca6db4daf1,ILD,R17,1347.0,245.0,2188.0,2169.0,2555,2285,MONOCHROME2
7,47ed17dcb2cbeec15182ed335a8b5a9e,Nodule/Mass,R9,557.0,2352.0,675.0,2484.0,3353,2568,MONOCHROME2
8,d3637a1935a905b3c326af31389cb846,Aortic enlargement,R10,1329.0,743.0,1521.0,958.0,2880,2304,MONOCHROME1
9,afb6230703512afc370f236e8fe98806,Pulmonary fibrosis,R9,1857.0,1607.0,2126.0,2036.0,3072,2540,MONOCHROME2

In [28]:
# ============================================================
# CONAN IMAGING — STEP 3
# Create normalized bounding-box features
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# 1. Identify rows that actually contain bounding boxes
# ------------------------------------------------------------

bbox_mask = (
    df["x_min"].notna()
    & df["y_min"].notna()
    & df["x_max"].notna()
    & df["y_max"].notna()
)

print("Total annotation rows:", len(df))
print("Rows with bounding boxes:", bbox_mask.sum())
print("Rows without bounding boxes:", (~bbox_mask).sum())

# ------------------------------------------------------------
# 2. Raw bounding-box dimensions
# ------------------------------------------------------------

df["box_width"] = np.where(
    bbox_mask,
    df["x_max"] - df["x_min"],
    np.nan
)

df["box_height"] = np.where(
    bbox_mask,
    df["y_max"] - df["y_min"],
    np.nan
)

df["box_area"] = (
    df["box_width"] *
    df["box_height"]
)

# ------------------------------------------------------------
# 3. Normalized bounding-box dimensions
# ------------------------------------------------------------

df["box_width_norm"] = (
    df["box_width"] / df["width"]
)

df["box_height_norm"] = (
    df["box_height"] / df["height"]
)

df["box_area_norm"] = (
    df["box_area"] /
    (df["width"] * df["height"])
)

# ------------------------------------------------------------
# 4. Bounding-box center
# ------------------------------------------------------------

df["center_x"] = (
    df["x_min"] + df["x_max"]
) / 2

df["center_y"] = (
    df["y_min"] + df["y_max"]
) / 2

# ------------------------------------------------------------
# 5. Normalize center to 0–1
# ------------------------------------------------------------

df["center_x_norm"] = (
    df["center_x"] / df["width"]
)

df["center_y_norm"] = (
    df["center_y"] / df["height"]
)

# ------------------------------------------------------------
# 6. Basic validity checks
# ------------------------------------------------------------

print("\nBounding-box feature ranges:")

display(
    df.loc[bbox_mask, [
        "box_width_norm",
        "box_height_norm",
        "box_area_norm",
        "center_x_norm",
        "center_y_norm"
    ]].describe()
)

# ------------------------------------------------------------
# 7. Check for invalid normalized values
# ------------------------------------------------------------

feature_cols = [
    "box_width_norm",
    "box_height_norm",
    "box_area_norm",
    "center_x_norm",
    "center_y_norm"
]

print("\nInvalid values:")

for col in feature_cols:
    invalid = (
        (df[col] < 0) |
        (df[col] > 1)
    ).sum()

    print(f"{col}: {invalid}")

# ------------------------------------------------------------
# 8. Preview
# ------------------------------------------------------------

print("\nFeature preview:")

display(
    df.loc[
        bbox_mask,
        [
            "image_id",
            "class_name",
            "rad_id",
            "box_width_norm",
            "box_height_norm",
            "box_area_norm",
            "center_x_norm",
            "center_y_norm"
        ]
    ].head(20)
)

Total annotation rows: 67914
Rows with bounding boxes: 36096
Rows without bounding boxes: 31818

Bounding-box feature ranges:

,box_width_norm,box_height_norm,box_area_norm,center_x_norm,center_y_norm
count,36096.000000,36096.000000,36096.000000,36096.000000,36096.000000
mean,0.176744,0.136923,0.030441,0.504143,0.441647
std,0.134128,0.112906,0.039812,0.209151,0.187271
min,0.003906,0.000989,0.000023,0.015625,0.022304
25%,0.084050,0.066319,0.005484,0.311686,0.298503
50%,0.128514,0.112892,0.014883,0.558858,0.410590
75%,0.232969,0.160764,0.044523,0.637238,0.590327
max,0.957212,0.980375,0.938427,0.983398,0.980566

Invalid values:
box_width_norm: 0
box_height_norm: 0
box_area_norm: 0
center_x_norm: 0
center_y_norm: 0

Feature preview:

,image_id,class_name,rad_id,box_width_norm,box_height_norm,box_area_norm,center_x_norm,center_y_norm
2,9a5094b2563a1ef3ff50dc5c7ff71345,Cardiomegaly,R10,0.462500,0.195205,0.090283,0.563462,0.686216
3,051132a778e61a86eb147c7c6f564dfe,Aortic enlargement,R10,0.150608,0.095833,0.014433,0.623915,0.305903
5,1c32170b4af4ce1a3030eb8167753b06,Pleural thickening,R9,0.125984,0.024740,0.003117,0.309843,0.128581
6,0c7a38f293d5f5e4846aa4ca6db4daf1,ILD,R17,0.368053,0.753033,0.277156,0.773523,0.472407
7,47ed17dcb2cbeec15182ed335a8b5a9e,Nodule/Mass,R9,0.045950,0.039368,0.001809,0.239875,0.721145
8,d3637a1935a905b3c326af31389cb846,Aortic enlargement,R10,0.083333,0.074653,0.006221,0.618490,0.295312
9,afb6230703512afc370f236e8fe98806,Pulmonary fibrosis,R9,0.105906,0.139648,0.014790,0.784055,0.592936
10,7c1add6833d5f0102b0d3619a1682a64,Lung Opacity,R10,0.102921,0.063371,0.006522,0.255265,0.473623
11,18a61a07e6f5f13ebfee57fa36cd8b6f,Pulmonary fibrosis,R9,0.186198,0.125000,0.023275,0.263672,0.160764
14,321c111713c3ee5385db0effb54ff568,Aortic enlargement,R8,0.080295,0.087153,0.006998,0.600911,0.235937
17,80caa435b6ab5edaff4a0a758ffaec6e,Atelectasis,R9,0.350883,0.612488,0.214912,0.285738,0.454940
18,5da264775732004f1b724b660138854a,Aortic enlargement,R9,0.111654,0.155599,0.017373,0.588053,0.296875
19,fb8e11c6b2886b2d41b379e0598669b9,Aortic enlargement,R10,0.098090,0.098958,0.009707,0.652344,0.354340
20,0622cd29e4e0e4f198abf15614819ae8,Cardiomegaly,R10,0.425171,0.146597,0.062329,0.633723,0.663800
22,347180362348e522905047dde655b6d7,Pleural thickening,R9,0.126465,0.025600,0.003237,0.627197,0.094400
27,22b8e616a61bbc4caaed0cf23b7159df,Pulmonary fibrosis,R10,0.104351,0.096420,0.010061,0.278945,0.299466
31,c394eadea89e5795c8037280492d116d,Other lesion,R9,0.118924,0.461458,0.054878,0.059462,0.522049
36,be1bb194dfb986bf7554b491852b8901,Lung Opacity,R9,0.092773,0.094727,0.008788,0.773275,0.547363
37,d7aea6f37597df566725da73655edcc2,Infiltration,R8,0.222822,0.260088,0.057953,0.792984,0.464948
39,8ae85268313b0db2f58d2193aab645c9,Other lesion,R10,0.163737,0.398438,0.065239,0.699707,0.475911

In [29]:
# ============================================================
# CONAN IMAGING — STEP 4
# Build image-level Nodule/Mass features
# ============================================================

# ------------------------------------------------------------
# 1. Select Nodule/Mass annotations
# ------------------------------------------------------------

nm = df[
    df["class_name"] == "Nodule/Mass"
].copy()

print("Nodule/Mass annotation rows:", len(nm))
print("Unique Nodule/Mass images:", nm["image_id"].nunique())

# ------------------------------------------------------------
# 2. Number of unique radiologists per image
# ------------------------------------------------------------

nm_radiologists = (
    nm.groupby("image_id")["rad_id"]
    .nunique()
    .rename("nodule_mass_radiologists")
)

# ------------------------------------------------------------
# 3. Annotation count per image
# ------------------------------------------------------------

nm_annotations = (
    nm.groupby("image_id")
    .size()
    .rename("nodule_mass_annotation_count")
)

# ------------------------------------------------------------
# 4. Radiologist agreement
# ------------------------------------------------------------

nm_agreement = (
    nm_radiologists / 3.0
).rename("nodule_mass_agreement")

# ------------------------------------------------------------
# 5. Aggregate normalized box measurements
# ------------------------------------------------------------

nm_size_location = (
    nm.groupby("image_id")
    .agg(
        nodule_mass_max_width=(
            "box_width_norm",
            "max"
        ),

        nodule_mass_mean_width=(
            "box_width_norm",
            "mean"
        ),

        nodule_mass_max_height=(
            "box_height_norm",
            "max"
        ),

        nodule_mass_mean_height=(
            "box_height_norm",
            "mean"
        ),

        nodule_mass_max_area=(
            "box_area_norm",
            "max"
        ),

        nodule_mass_mean_area=(
            "box_area_norm",
            "mean"
        ),

        nodule_mass_mean_x=(
            "center_x_norm",
            "mean"
        ),

        nodule_mass_mean_y=(
            "center_y_norm",
            "mean"
        ),

        nodule_mass_min_x=(
            "center_x_norm",
            "min"
        ),

        nodule_mass_max_x=(
            "center_x_norm",
            "max"
        ),

        nodule_mass_min_y=(
            "center_y_norm",
            "min"
        ),

        nodule_mass_max_y=(
            "center_y_norm",
            "max"
        )
    )
)

# ------------------------------------------------------------
# 6. Combine Nodule/Mass features
# ------------------------------------------------------------

nodule_features = pd.concat(
    [
        nm_radiologists,
        nm_annotations,
        nm_agreement,
        nm_size_location
    ],
    axis=1
).reset_index()

# ------------------------------------------------------------
# 7. Explicit presence flag
# ------------------------------------------------------------

nodule_features["nodule_mass_present"] = 1

# ------------------------------------------------------------
# 8. Display result
# ------------------------------------------------------------

print("\nNodule/Mass image-level dataset:")
print("Rows:", len(nodule_features))
print("Columns:", len(nodule_features.columns))

display(nodule_features.head(20))

Nodule/Mass annotation rows: 2580
Unique Nodule/Mass images: 826

Nodule/Mass image-level dataset:
Rows: 826
Columns: 17

,image_id,nodule_mass_radiologists,nodule_mass_annotation_count,nodule_mass_agreement,nodule_mass_max_width,nodule_mass_mean_width,nodule_mass_max_height,nodule_mass_mean_height,nodule_mass_max_area,nodule_mass_mean_area,nodule_mass_mean_x,nodule_mass_mean_y,nodule_mass_min_x,nodule_mass_max_x,nodule_mass_min_y,nodule_mass_max_y,nodule_mass_present
0,0005e8e3701dfb1dd93d53e2ff537b6e,1,1,0.333333,0.086263,0.086263,0.107096,0.107096,0.009238,0.009238,0.346517,0.238118,0.346517,0.346517,0.238118,0.238118,1
1,0061cf6d35e253b6e7f03940592cc35e,1,1,0.333333,0.042520,0.042520,0.020833,0.020833,0.000886,0.000886,0.288189,0.235352,0.288189,0.288189,0.235352,0.235352,1
2,008b3176a7248a0a189b5731ac8d2e95,3,6,1.000000,0.073852,0.057751,0.053384,0.044752,0.003661,0.002703,0.751430,0.446007,0.674251,0.795010,0.341913,0.503972,1
3,010018c93ed33ae56ed048ee54867e46,2,3,0.666667,0.019197,0.015997,0.019550,0.015097,0.000375,0.000249,0.324742,0.335994,0.298614,0.338606,0.304659,0.352069,1
4,011ae9520e81f1efe71c9d954ec07d09,1,1,0.333333,0.019857,0.019857,0.023763,0.023763,0.000472,0.000472,0.815267,0.601725,0.815267,0.815267,0.601725,0.601725,1
5,01546d3e6175ceaabd7d92f0c566579d,2,2,0.666667,0.019759,0.019759,0.015137,0.013403,0.000299,0.000265,0.154226,0.510170,0.153311,0.155141,0.508830,0.511511,1
6,0162dad8330007f8f0daf43bcf4033f1,1,1,0.333333,0.010091,0.010091,0.006185,0.006185,0.000062,0.000062,0.311035,0.179850,0.311035,0.311035,0.179850,0.179850,1
7,01a3c3d994d85ce5634d2d13c03fd4b0,3,3,1.000000,0.122721,0.110026,0.101888,0.097114,0.011625,0.010657,0.328016,0.375705,0.325684,0.329264,0.373210,0.378743,1
8,01ee6e560f083255a630c41bba779405,2,2,0.666667,0.032292,0.031510,0.036517,0.035815,0.001134,0.001128,0.763411,0.246372,0.761719,0.765104,0.246255,0.246489,1
9,0211f9fe31142ba1e25fb6a2ea3fea38,2,2,0.666667,0.018229,0.017361,0.013889,0.013542,0.000253,0.000235,0.748047,0.273611,0.746962,0.749132,0.273611,0.273611,1
10,023a8b8557d1fd59f272c63be6f3d4c0,2,4,0.666667,0.022232,0.018561,0.029038,0.021053,0.000646,0.000411,0.099255,0.732577,0.081586,0.115772,0.705082,0.759891,1
11,024f9140bd829c346fc91fcf4009d251,1,3,0.333333,0.288538,0.186609,0.486331,0.331775,0.140325,0.069546,0.412025,0.513609,0.174632,0.689364,0.363849,0.700000,1
12,02562eb68a9c682f5f644fa7a099733f,2,8,0.666667,0.025174,0.018989,0.025000,0.018012,0.000629,0.000363,0.610460,0.368555,0.245009,0.750434,0.331597,0.445833,1
13,02fe3eea41166a1d3eb75307a12c4a63,2,6,0.666667,0.051901,0.041058,0.040232,0.034814,0.002088,0.001484,0.730507,0.284117,0.695906,0.763706,0.205826,0.372385,1
14,033e1637bed9b9f3dccac9c6c419adc2,2,4,0.666667,0.061239,0.049756,0.056928,0.042931,0.003486,0.002217,0.840640,0.395566,0.815762,0.866736,0.363935,0.425399,1
15,035480fbf46e946e21e7dce78637c329,1,2,0.333333,0.046610,0.046345,0.040138,0.037271,0.001850,0.001727,0.524762,0.595470,0.286811,0.762712,0.589067,0.601873,1
16,03e6ecfa6f6fb33dfeac6ca4f9b459c9,3,55,1.000000,0.338617,0.043699,0.668115,0.056065,0.226235,0.009421,0.464075,0.523055,0.143912,0.929755,0.264205,0.828041,1
17,04031e57794b9e8861e3c65e935f11d2,3,3,1.000000,0.158854,0.143446,0.186198,0.178711,0.029578,0.025693,0.763129,0.431044,0.757487,0.767578,0.427897,0.434245,1
18,0453de2faeb8d349af739a68d9dee1cb,2,2,0.666667,0.049316,0.048828,0.043600,0.042200,0.002150,0.002061,0.792236,0.615100,0.791748,0.792725,0.614000,0.616200,1
19,04aed38b30c4de9461c8a9940e99d811,1,1,0.333333,0.021016,0.021016,0.013815,0.013815,0.000290,0.000290,0.745009,0.505313,0.745009,0.745009,0.505313,0.505313,1

In [30]:
# ============================================================
# VERIFY NODULE/MASS AGREEMENT
# ============================================================

print("Radiologists identifying Nodule/Mass:")

display(
    nodule_features[
        "nodule_mass_radiologists"
    ]
    .value_counts()
    .sort_index()
    .rename_axis("radiologists")
    .reset_index(name="images")
)

print("\nAgreement distribution:")

display(
    nodule_features[
        "nodule_mass_agreement"
    ]
    .value_counts()
    .sort_index()
    .rename_axis("agreement")
    .reset_index(name="images")
)

print("\nAnnotation count distribution:")

display(
    nodule_features[
        "nodule_mass_annotation_count"
    ].describe()
)

Radiologists identifying Nodule/Mass:

   radiologists  images
0             1     421
1             2     224
2             3     181

Agreement distribution:

   agreement  images
0   0.333333     421
1   0.666667     224
2   1.000000     181

Annotation count distribution:

count    826.000000
mean       3.123487
std        4.557964
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       55.000000
Name: nodule_mass_annotation_count, dtype: float64

In [31]:
# ============================================================
# CONAN IMAGING — COMPLETE NODULE/MASS FEATURE TABLE
# ============================================================

# Get one row per image from the original dataset
image_base = (
    df[
        [
            "image_id",
            "height",
            "width",
            "photometric"
        ]
    ]
    .drop_duplicates("image_id")
    .copy()
)

print("Unique images:", len(image_base))

# Merge Nodule/Mass features
imaging_nm = image_base.merge(
    nodule_features,
    on="image_id",
    how="left"
)

# ------------------------------------------------------------
# Fill values for images without Nodule/Mass
# ------------------------------------------------------------

zero_columns = [
    "nodule_mass_radiologists",
    "nodule_mass_annotation_count",
    "nodule_mass_agreement",
    "nodule_mass_present"
]

for col in zero_columns:
    imaging_nm[col] = (
        imaging_nm[col]
        .fillna(0)
    )

# Size/location features are undefined when
# no Nodule/Mass exists.
# For a risk model, zero provides a clear
# "no lesion evidence" representation.

feature_zero_columns = [
    "nodule_mass_max_width",
    "nodule_mass_mean_width",
    "nodule_mass_max_height",
    "nodule_mass_mean_height",
    "nodule_mass_max_area",
    "nodule_mass_mean_area",
    "nodule_mass_mean_x",
    "nodule_mass_mean_y",
    "nodule_mass_min_x",
    "nodule_mass_max_x",
    "nodule_mass_min_y",
    "nodule_mass_max_y"
]

for col in feature_zero_columns:
    imaging_nm[col] = (
        imaging_nm[col]
        .fillna(0)
    )

# ------------------------------------------------------------
# Final verification
# ------------------------------------------------------------

print("\nFINAL NODULE/MASS TABLE")
print("-----------------------")
print("Rows:", len(imaging_nm))
print("Columns:", len(imaging_nm.columns))

print("\nNodule/Mass presence:")
display(
    imaging_nm[
        "nodule_mass_present"
    ]
    .value_counts()
    .sort_index()
    .rename_axis("present")
    .reset_index(name="images")
)

print("\nMissing values:")
display(
    imaging_nm.isnull().sum()
)

print("\nPreview:")
display(
    imaging_nm.head(10)
)

Unique images: 15000

FINAL NODULE/MASS TABLE
-----------------------
Rows: 15000
Columns: 20

Nodule/Mass presence:

   present  images
0      0.0   14174
1      1.0     826

Missing values:

image_id                        0
height                          0
width                           0
photometric                     0
nodule_mass_radiologists        0
nodule_mass_annotation_count    0
nodule_mass_agreement           0
nodule_mass_max_width           0
nodule_mass_mean_width          0
nodule_mass_max_height          0
nodule_mass_mean_height         0
nodule_mass_max_area            0
nodule_mass_mean_area           0
nodule_mass_mean_x              0
nodule_mass_mean_y              0
nodule_mass_min_x               0
nodule_mass_max_x               0
nodule_mass_min_y               0
nodule_mass_max_y               0
nodule_mass_present             0
dtype: int64

Preview:

,image_id,height,width,photometric,nodule_mass_radiologists,nodule_mass_annotation_count,nodule_mass_agreement,nodule_mass_max_width,nodule_mass_mean_width,nodule_mass_max_height,nodule_mass_mean_height,nodule_mass_max_area,nodule_mass_mean_area,nodule_mass_mean_x,nodule_mass_mean_y,nodule_mass_min_x,nodule_mass_max_x,nodule_mass_min_y,nodule_mass_max_y,nodule_mass_present
0,50a418190bc3fb1ef1633bf9678929b3,2580,2332,MONOCHROME2,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
1,21a10246a5ec7af151081d0cd6d65dc9,3159,2954,MONOCHROME2,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
2,9a5094b2563a1ef3ff50dc5c7ff71345,2336,2080,MONOCHROME1,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,051132a778e61a86eb147c7c6f564dfe,2880,2304,MONOCHROME1,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
4,063319de25ce7edb9b1c6b8881290140,3072,2540,MONOCHROME2,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
5,1c32170b4af4ce1a3030eb8167753b06,3072,2540,MONOCHROME2,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
6,0c7a38f293d5f5e4846aa4ca6db4daf1,2555,2285,MONOCHROME2,1.0,1.0,0.333333,0.092341,0.092341,0.066536,0.066536,0.006144,0.006144,0.246608,0.343249,0.246608,0.246608,0.343249,0.343249,1.0
7,47ed17dcb2cbeec15182ed335a8b5a9e,3353,2568,MONOCHROME2,3.0,3.0,1.000000,0.050623,0.045301,0.041754,0.038374,0.002114,0.001753,0.238512,0.719356,0.237150,0.239875,0.716672,0.721145,1.0
8,d3637a1935a905b3c326af31389cb846,2880,2304,MONOCHROME1,1.0,3.0,0.333333,0.029514,0.023872,0.018056,0.014699,0.000533,0.000365,0.242694,0.635822,0.232205,0.253906,0.616493,0.652431,1.0
9,afb6230703512afc370f236e8fe98806,3072,2540,MONOCHROME2,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0

In [32]:
# ============================================================
# CONAN IMAGING — STEP 4 VERIFICATION
# ============================================================

print("Nodule/Mass radiologist agreement")
print("=" * 50)

agreement_table = (
    nodule_features[
        "nodule_mass_radiologists"
    ]
    .value_counts()
    .sort_index()
    .rename_axis("radiologists_identifying_nodule_mass")
    .reset_index(name="number_of_images")
)

display(agreement_table)


print("\nAgreement proportions")
print("=" * 50)

agreement_proportion = (
    nodule_features[
        "nodule_mass_agreement"
    ]
    .value_counts()
    .sort_index()
    .rename_axis("agreement")
    .reset_index(name="number_of_images")
)

agreement_proportion["percentage"] = (
    agreement_proportion["number_of_images"]
    / len(nodule_features)
    * 100
)

display(agreement_proportion)


print("\nAnnotation count statistics")
print("=" * 50)

display(
    nodule_features[
        "nodule_mass_annotation_count"
    ].describe()
)


print("\nCheck total Nodule/Mass images:")
print(
    "Total:",
    len(nodule_features)
)

Nodule/Mass radiologist agreement
==================================================

   radiologists_identifying_nodule_mass  number_of_images
0                                     1               421
1                                     2               224
2                                     3               181

Agreement proportions
==================================================

   agreement  number_of_images  percentage
0   0.333333               421   50.968523
1   0.666667               224   27.118644
2   1.000000               181   21.912833

Annotation count statistics
==================================================

count    826.000000
mean       3.123487
std        4.557964
min        1.000000
25%        1.000000
50%        2.000000
75%        3.000000
max       55.000000
Name: nodule_mass_annotation_count, dtype: float64

Check total Nodule/Mass images:
Total: 826

In [33]:
# ============================================================
# CONAN IMAGING — STEP 5
# Build complete image-level radiographic feature matrix
# ============================================================

import numpy as np
import pandas as pd

# ------------------------------------------------------------
# 1. Define actual abnormality classes
# ------------------------------------------------------------

abnormalities = [
    "Aortic enlargement",
    "Cardiomegaly",
    "Pleural thickening",
    "ILD",
    "Nodule/Mass",
    "Pulmonary fibrosis",
    "Lung Opacity",
    "Atelectasis",
    "Other lesion",
    "Infiltration",
    "Pleural effusion",
    "Calcification",
    "Consolidation",
    "Pneumothorax"
]

print("Number of abnormality classes:", len(abnormalities))
print(abnormalities)

# ------------------------------------------------------------
# 2. Start with exactly one row per X-ray
# ------------------------------------------------------------

image_features = (
    df[
        [
            "image_id",
            "height",
            "width",
            "photometric"
        ]
    ]
    .drop_duplicates("image_id")
    .copy()
)

print("\nInitial image table:")
print("Rows:", len(image_features))

# ------------------------------------------------------------
# 3. Process each abnormality
# ------------------------------------------------------------

for abnormality in abnormalities:

    # Create a safe column prefix
    prefix = (
        abnormality
        .lower()
        .replace("/", "_")
        .replace(" ", "_")
    )

    # Select annotations for this abnormality
    subset = df[
        df["class_name"] == abnormality
    ].copy()

    if len(subset) == 0:
        print(f"WARNING: No annotations for {abnormality}")
        continue

    # --------------------------------------------------------
    # Radiologist count
    # --------------------------------------------------------

    radiologist_count = (
        subset.groupby("image_id")["rad_id"]
        .nunique()
        .rename(
            f"{prefix}_radiologists"
        )
    )

    # --------------------------------------------------------
    # Annotation count
    # --------------------------------------------------------

    annotation_count = (
        subset.groupby("image_id")
        .size()
        .rename(
            f"{prefix}_annotation_count"
        )
    )

    # --------------------------------------------------------
    # Agreement
    #
    # Each VinBigData image was evaluated by 3 radiologists.
    # --------------------------------------------------------

    agreement = (
        radiologist_count / 3.0
    ).rename(
        f"{prefix}_agreement"
    )

    # --------------------------------------------------------
    # Spatial and size features
    # --------------------------------------------------------

    measurements = (
        subset.groupby("image_id")
        .agg(

            max_width=(
                "box_width_norm",
                "max"
            ),

            mean_width=(
                "box_width_norm",
                "mean"
            ),

            max_height=(
                "box_height_norm",
                "max"
            ),

            mean_height=(
                "box_height_norm",
                "mean"
            ),

            max_area=(
                "box_area_norm",
                "max"
            ),

            mean_area=(
                "box_area_norm",
                "mean"
            ),

            mean_x=(
                "center_x_norm",
                "mean"
            ),

            mean_y=(
                "center_y_norm",
                "mean"
            )
        )
    )

    # Rename measurement columns
    measurements = measurements.rename(
        columns={
            "max_width":
                f"{prefix}_max_width",

            "mean_width":
                f"{prefix}_mean_width",

            "max_height":
                f"{prefix}_max_height",

            "mean_height":
                f"{prefix}_mean_height",

            "max_area":
                f"{prefix}_max_area",

            "mean_area":
                f"{prefix}_mean_area",

            "mean_x":
                f"{prefix}_mean_x",

            "mean_y":
                f"{prefix}_mean_y"
        }
    )

    # --------------------------------------------------------
    # Combine this abnormality's features
    # --------------------------------------------------------

    abnormality_features = pd.concat(
        [
            radiologist_count,
            annotation_count,
            agreement,
            measurements
        ],
        axis=1
    ).reset_index()

    # --------------------------------------------------------
    # Presence indicator
    # --------------------------------------------------------

    abnormality_features[
        f"{prefix}_present"
    ] = 1

    # --------------------------------------------------------
    # Merge into master image table
    # --------------------------------------------------------

    image_features = image_features.merge(
        abnormality_features,
        on="image_id",
        how="left",
        validate="one_to_one"
    )

    # --------------------------------------------------------
    # Fill absence with zero
    # --------------------------------------------------------

    new_columns = [
        c for c in abnormality_features.columns
        if c != "image_id"
    ]

    image_features[new_columns] = (
        image_features[new_columns]
        .fillna(0)
    )

    print(
        f"{abnormality:25s} → "
        f"{len(subset):5d} annotations | "
        f"{subset['image_id'].nunique():5d} images"
    )

# ------------------------------------------------------------
# 4. Final dimensions
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FINAL RADIOGRAPHIC FEATURE MATRIX")
print("=" * 70)

print("Images:", len(image_features))
print("Features:", len(image_features.columns))

print("\nShape:")
print(image_features.shape)

# ------------------------------------------------------------
# 5. Verify no duplicate image IDs
# ------------------------------------------------------------

print(
    "\nDuplicate image IDs:",
    image_features["image_id"].duplicated().sum()
)

# ------------------------------------------------------------
# 6. Missing-value check
# ------------------------------------------------------------

missing = (
    image_features
    .isnull()
    .sum()
)

print("\nColumns with missing values:")
display(
    missing[missing > 0]
)

# ------------------------------------------------------------
# 7. Display presence counts
# ------------------------------------------------------------

presence_columns = [
    c for c in image_features.columns
    if c.endswith("_present")
]

presence_summary = []

for col in presence_columns:

    presence_summary.append({
        "feature": col,
        "images_present":
            int(image_features[col].sum()),
        "percentage":
            float(
                image_features[col].mean() * 100
            )
    })

presence_summary = pd.DataFrame(
    presence_summary
).sort_values(
    "images_present",
    ascending=False
)

print("\nAbnormality presence:")
display(presence_summary)

# ------------------------------------------------------------
# 8. Preview
# ------------------------------------------------------------

print("\nFeature matrix preview:")
display(
    image_features.head()
)

Number of abnormality classes: 14
['Aortic enlargement', 'Cardiomegaly', 'Pleural thickening', 'ILD', 'Nodule/Mass', 'Pulmonary fibrosis', 'Lung Opacity', 'Atelectasis', 'Other lesion', 'Infiltration', 'Pleural effusion', 'Calcification', 'Consolidation', 'Pneumothorax']

Initial image table:
Rows: 15000
Aortic enlargement        →  7162 annotations |  3067 images
Cardiomegaly              →  5427 annotations |  2300 images
Pleural thickening        →  4842 annotations |  1981 images
ILD                       →  1000 annotations |   386 images
Nodule/Mass               →  2580 annotations |   826 images
Pulmonary fibrosis        →  4655 annotations |  1617 images
Lung Opacity              →  2483 annotations |  1322 images
Atelectasis               →   279 annotations |   186 images
Other lesion              →  2203 annotations |  1134 images
Infiltration              →  1247 annotations |   613 images
Pleural effusion          →  2476 annotations |  1032 images
Calcification             →   960 annotations |   452 images
Consolidation             →   556 annotations |   353 images
Pneumothorax              →   226 annotations |    96 images

======================================================================
FINAL RADIOGRAPHIC FEATURE MATRIX
======================================================================
Images: 15000
Features: 172

Shape:
(15000, 172)

Duplicate image IDs: 0

Columns with missing values:

Series([], dtype: int64)

Abnormality presence:

                       feature  images_present  percentage
0   aortic_enlargement_present            3067   20.446667
1         cardiomegaly_present            2300   15.333333
2   pleural_thickening_present            1981   13.206667
5   pulmonary_fibrosis_present            1617   10.780000
6         lung_opacity_present            1322    8.813333
8         other_lesion_present            1134    7.560000
10    pleural_effusion_present            1032    6.880000
4          nodule_mass_present             826    5.506667
9         infiltration_present             613    4.086667
11       calcification_present             452    3.013333
3                  ild_present             386    2.573333
12       consolidation_present             353    2.353333
7          atelectasis_present             186    1.240000
13        pneumothorax_present              96    0.640000

Feature matrix preview:

,image_id,height,width,photometric,aortic_enlargement_radiologists,aortic_enlargement_annotation_count,aortic_enlargement_agreement,aortic_enlargement_max_width,aortic_enlargement_mean_width,aortic_enlargement_max_height,...,pneumothorax_agreement,pneumothorax_max_width,pneumothorax_mean_width,pneumothorax_max_height,pneumothorax_mean_height,pneumothorax_max_area,pneumothorax_mean_area,pneumothorax_mean_x,pneumothorax_mean_y,pneumothorax_present
0,50a418190bc3fb1ef1633bf9678929b3,2580,2332,MONOCHROME2,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21a10246a5ec7af151081d0cd6d65dc9,3159,2954,MONOCHROME2,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,9a5094b2563a1ef3ff50dc5c7ff71345,2336,2080,MONOCHROME1,1.0,1.0,0.333333,0.118750,0.118750,0.107449,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,051132a778e61a86eb147c7c6f564dfe,2880,2304,MONOCHROME1,3.0,3.0,1.000000,0.150608,0.143519,0.117014,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,063319de25ce7edb9b1c6b8881290140,3072,2540,MONOCHROME2,0.0,0.0,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
# ============================================================
# CONAN IMAGING — STEP 6
# Create interpretable candidate imaging predictors
# ============================================================

# ------------------------------------------------------------
# Abnormality prefixes
# ------------------------------------------------------------

abnormality_prefixes = [
    "aortic_enlargement",
    "cardiomegaly",
    "pleural_thickening",
    "ild",
    "nodule_mass",
    "pulmonary_fibrosis",
    "lung_opacity",
    "atelectasis",
    "other_lesion",
    "infiltration",
    "pleural_effusion",
    "calcification",
    "consolidation",
    "pneumothorax"
]

# ------------------------------------------------------------
# Candidate features
#
# We intentionally DO NOT include:
# - radiologists
# - annotation_count
#
# because these are highly related to agreement and can
# introduce redundant information.
# ------------------------------------------------------------

candidate_columns = [
    "image_id",
    "height",
    "width",
    "photometric"
]

for prefix in abnormality_prefixes:

    candidate_columns.extend([
        f"{prefix}_present",
        f"{prefix}_agreement",
        f"{prefix}_mean_area",
        f"{prefix}_mean_width",
        f"{prefix}_mean_height",
        f"{prefix}_mean_x",
        f"{prefix}_mean_y"
    ])

candidate_features = image_features[
    candidate_columns
].copy()

# ------------------------------------------------------------
# Verify
# ------------------------------------------------------------

print("=" * 70)
print("CANDIDATE IMAGING FEATURE MATRIX")
print("=" * 70)

print("Rows:", candidate_features.shape[0])
print("Columns:", candidate_features.shape[1])

print("\nShape:")
print(candidate_features.shape)

print("\nMissing values:")
print(
    candidate_features.isnull().sum().sum()
)

print("\nDuplicate image IDs:")
print(
    candidate_features["image_id"].duplicated().sum()
)

# ------------------------------------------------------------
# Count candidate predictors
# ------------------------------------------------------------

predictor_columns = [
    c for c in candidate_features.columns
    if c not in [
        "image_id",
        "height",
        "width",
        "photometric"
    ]
]

print("\nNumber of candidate predictors:")
print(len(predictor_columns))

# ------------------------------------------------------------
# Show columns
# ------------------------------------------------------------

print("\nCandidate predictors:")

for i, col in enumerate(predictor_columns, 1):
    print(f"{i:02d}. {col}")

# ------------------------------------------------------------
# Save for next step
# ------------------------------------------------------------

candidate_features.to_csv(
    "/kaggle/working/conan_imaging_candidate_features.csv",
    index=False
)

print(
    "\nSaved:"
    "\n/kaggle/working/conan_imaging_candidate_features.csv"
)

======================================================================
CANDIDATE IMAGING FEATURE MATRIX
======================================================================
Rows: 15000
Columns: 102

Shape:
(15000, 102)

Missing values:
0

Duplicate image IDs:
0

Number of candidate predictors:
98

Candidate predictors:
01. aortic_enlargement_present
02. aortic_enlargement_agreement
03. aortic_enlargement_mean_area
04. aortic_enlargement_mean_width
05. aortic_enlargement_mean_height
06. aortic_enlargement_mean_x
07. aortic_enlargement_mean_y
08. cardiomegaly_present
09. cardiomegaly_agreement
10. cardiomegaly_mean_area
11. cardiomegaly_mean_width
12. cardiomegaly_mean_height
13. cardiomegaly_mean_x
14. cardiomegaly_mean_y
15. pleural_thickening_present
16. pleural_thickening_agreement
17. pleural_thickening_mean_area
18. pleural_thickening_mean_width
19. pleural_thickening_mean_height
20. pleural_thickening_mean_x
21. pleural_thickening_mean_y
22. ild_present
23. ild_agreement
24. ild_mean_area
25. ild_mean_width
26. ild_mean_height
27. ild_mean_x
28. ild_mean_y
29. nodule_mass_present
30. nodule_mass_agreement
31. nodule_mass_mean_area
32. nodule_mass_mean_width
33. nodule_mass_mean_height
34. nodule_mass_mean_x
35. nodule_mass_mean_y
36. pulmonary_fibrosis_present
37. pulmonary_fibrosis_agreement
38. pulmonary_fibrosis_mean_area
39. pulmonary_fibrosis_mean_width
40. pulmonary_fibrosis_mean_height
41. pulmonary_fibrosis_mean_x
42. pulmonary_fibrosis_mean_y
43. lung_opacity_present
44. lung_opacity_agreement
45. lung_opacity_mean_area
46. lung_opacity_mean_width
47. lung_opacity_mean_height
48. lung_opacity_mean_x
49. lung_opacity_mean_y
50. atelectasis_present
51. atelectasis_agreement
52. atelectasis_mean_area
53. atelectasis_mean_width
54. atelectasis_mean_height
55. atelectasis_mean_x
56. atelectasis_mean_y
57. other_lesion_present
58. other_lesion_agreement
59. other_lesion_mean_area
60. other_lesion_mean_width
61. other_lesion_mean_height
62. other_lesion_mean_x
63. other_lesion_mean_y
64. infiltration_present
65. infiltration_agreement
66. infiltration_mean_area
67. infiltration_mean_width
68. infiltration_mean_height
69. infiltration_mean_x
70. infiltration_mean_y
71. pleural_effusion_present
72. pleural_effusion_agreement
73. pleural_effusion_mean_area
74. pleural_effusion_mean_width
75. pleural_effusion_mean_height
76. pleural_effusion_mean_x
77. pleural_effusion_mean_y
78. calcification_present
79. calcification_agreement
80. calcification_mean_area
81. calcification_mean_width
82. calcification_mean_height
83. calcification_mean_x
84. calcification_mean_y
85. consolidation_present
86. consolidation_agreement
87. consolidation_mean_area
88. consolidation_mean_width
89. consolidation_mean_height
90. consolidation_mean_x
91. consolidation_mean_y
92. pneumothorax_present
93. pneumothorax_agreement
94. pneumothorax_mean_area
95. pneumothorax_mean_width
96. pneumothorax_mean_height
97. pneumothorax_mean_x
98. pneumothorax_mean_y

Saved:
/kaggle/working/conan_imaging_candidate_features.csv

In [36]:
import os

print("Searching for JSRT metadata...")
print("=" * 70)

matches = []

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if "jsrt" in file.lower() or "metadata" in file.lower():
            matches.append(os.path.join(root, file))

for root, dirs, files in os.walk("/kaggle/working"):
    for file in files:
        if "jsrt" in file.lower() or "metadata" in file.lower():
            matches.append(os.path.join(root, file))

if matches:
    print("FOUND:")
    for path in matches:
        print(path)
else:
    print("NO JSRT FILE FOUND.")

Searching for JSRT metadata...
======================================================================
FOUND:
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv

In [40]:
import pandas as pd

FEATURE_PATH = "/kaggle/working/conan_imaging_candidate_features.csv"

df = pd.read_csv(FEATURE_PATH)

print("=" * 70)
print("CONAN IMAGING FEATURE MATRIX")
print("=" * 70)

print("Shape:", df.shape)
print("\nColumns:", len(df.columns))
print("\nMissing values:", df.isnull().sum().sum())
print("Duplicate image IDs:", df["image_id"].duplicated().sum())

print("\nFirst 5 rows:")
display(df.head())

======================================================================
CONAN IMAGING FEATURE MATRIX
======================================================================
Shape: (15000, 102)

Columns: 102

Missing values: 0
Duplicate image IDs: 0

First 5 rows:

,image_id,height,width,photometric,aortic_enlargement_present,aortic_enlargement_agreement,aortic_enlargement_mean_area,aortic_enlargement_mean_width,aortic_enlargement_mean_height,aortic_enlargement_mean_x,...,consolidation_mean_height,consolidation_mean_x,consolidation_mean_y,pneumothorax_present,pneumothorax_agreement,pneumothorax_mean_area,pneumothorax_mean_width,pneumothorax_mean_height,pneumothorax_mean_x,pneumothorax_mean_y
0,50a418190bc3fb1ef1633bf9678929b3,2580,2332,MONOCHROME2,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21a10246a5ec7af151081d0cd6d65dc9,3159,2954,MONOCHROME2,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,9a5094b2563a1ef3ff50dc5c7ff71345,2336,2080,MONOCHROME1,1.0,0.333333,0.012760,0.118750,0.107449,0.565144,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,051132a778e61a86eb147c7c6f564dfe,2880,2304,MONOCHROME1,1.0,1.000000,0.015699,0.143519,0.109722,0.627894,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,063319de25ce7edb9b1c6b8881290140,3072,2540,MONOCHROME2,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
import pandas as pd
import numpy as np

FEATURE_PATH = "/kaggle/working/conan_imaging_candidate_features.csv"

df = pd.read_csv(FEATURE_PATH)

# Metadata — NOT model predictors
metadata_cols = [
    "image_id",
    "height",
    "width",
    "photometric"
]

# Candidate imaging predictors
predictor_cols = [
    c for c in df.columns
    if c not in metadata_cols
]

X = df[predictor_cols].copy()

print("=" * 70)
print("CONAN — IMAGING PREDICTOR SET")
print("=" * 70)

print("Total images:", len(df))
print("Metadata columns:", len(metadata_cols))
print("Candidate predictors:", len(predictor_cols))
print("Predictor matrix:", X.shape)

print("\nMetadata:")
print(metadata_cols)

print("\nPredictor types:")
print(X.dtypes.value_counts())

print("\nConstant predictors:")
constant_cols = [
    c for c in predictor_cols
    if X[c].nunique(dropna=False) <= 1
]

print("Count:", len(constant_cols))

if constant_cols:
    print(constant_cols)

print("\nPredictors with non-zero values:")
for c in predictor_cols:
    nonzero = (X[c] != 0).sum()
    if nonzero > 0:
        print(f"{c:45s} {nonzero:6d} ({nonzero/len(X)*100:6.2f}%)")

======================================================================
CONAN — IMAGING PREDICTOR SET
======================================================================
Total images: 15000
Metadata columns: 4
Candidate predictors: 98
Predictor matrix: (15000, 98)

Metadata:
['image_id', 'height', 'width', 'photometric']

Predictor types:
float64    98
Name: count, dtype: int64

Constant predictors:
Count: 0

Predictors with non-zero values:
aortic_enlargement_present                      3067 ( 20.45%)
aortic_enlargement_agreement                    3067 ( 20.45%)
aortic_enlargement_mean_area                    3067 ( 20.45%)
aortic_enlargement_mean_width                   3067 ( 20.45%)
aortic_enlargement_mean_height                  3067 ( 20.45%)
aortic_enlargement_mean_x                       3067 ( 20.45%)
aortic_enlargement_mean_y                       3067 ( 20.45%)
cardiomegaly_present                            2300 ( 15.33%)
cardiomegaly_agreement                          2300 ( 15.33%)
cardiomegaly_mean_area                          2300 ( 15.33%)
cardiomegaly_mean_width                         2300 ( 15.33%)
cardiomegaly_mean_height                        2300 ( 15.33%)
cardiomegaly_mean_x                             2300 ( 15.33%)
cardiomegaly_mean_y                             2300 ( 15.33%)
pleural_thickening_present                      1981 ( 13.21%)
pleural_thickening_agreement                    1981 ( 13.21%)
pleural_thickening_mean_area                    1981 ( 13.21%)
pleural_thickening_mean_width                   1981 ( 13.21%)
pleural_thickening_mean_height                  1981 ( 13.21%)
pleural_thickening_mean_x                       1981 ( 13.21%)
pleural_thickening_mean_y                       1981 ( 13.21%)
ild_present                                      386 (  2.57%)
ild_agreement                                    386 (  2.57%)
ild_mean_area                                    386 (  2.57%)
ild_mean_width                                   386 (  2.57%)
ild_mean_height                                  386 (  2.57%)
ild_mean_x                                       386 (  2.57%)
ild_mean_y                                       386 (  2.57%)
nodule_mass_present                              826 (  5.51%)
nodule_mass_agreement                            826 (  5.51%)
nodule_mass_mean_area                            826 (  5.51%)
nodule_mass_mean_width                           826 (  5.51%)
nodule_mass_mean_height                          826 (  5.51%)
nodule_mass_mean_x                               826 (  5.51%)
nodule_mass_mean_y                               826 (  5.51%)
pulmonary_fibrosis_present                      1617 ( 10.78%)
pulmonary_fibrosis_agreement                    1617 ( 10.78%)
pulmonary_fibrosis_mean_area                    1617 ( 10.78%)
pulmonary_fibrosis_mean_width                   1617 ( 10.78%)
pulmonary_fibrosis_mean_height                  1617 ( 10.78%)
pulmonary_fibrosis_mean_x                       1617 ( 10.78%)
pulmonary_fibrosis_mean_y                       1617 ( 10.78%)
lung_opacity_present                            1322 (  8.81%)
lung_opacity_agreement                          1322 (  8.81%)
lung_opacity_mean_area                          1322 (  8.81%)
lung_opacity_mean_width                         1322 (  8.81%)
lung_opacity_mean_height                        1322 (  8.81%)
lung_opacity_mean_x                             1322 (  8.81%)
lung_opacity_mean_y                             1322 (  8.81%)
atelectasis_present                              186 (  1.24%)
atelectasis_agreement                            186 (  1.24%)
atelectasis_mean_area                            186 (  1.24%)
atelectasis_mean_width                           186 (  1.24%)
atelectasis_mean_height                          186 (  1.24%)
atelectasis_mean_x                               186 (  1.24%)
atelectasis_mean_y                               186 (  1.24%)
other_lesion_present                            1134 (  7.56%)
other_lesion_agreement                          1134 (  7.56%)
other_lesion_mean_area                          1134 (  7.56%)
other_lesion_mean_width                         1134 (  7.56%)
other_lesion_mean_height                        1134 (  7.56%)
other_lesion_mean_x                             1134 (  7.56%)
other_lesion_mean_y                             1134 (  7.56%)
infiltration_present                             613 (  4.09%)
infiltration_agreement                           613 (  4.09%)
infiltration_mean_area                           613 (  4.09%)
infiltration_mean_width                          613 (  4.09%)
infiltration_mean_height                         613 (  4.09%)
infiltration_mean_x                              613 (  4.09%)
infiltration_mean_y                              613 (  4.09%)
pleural_effusion_present                        1032 (  6.88%)
pleural_effusion_agreement                      1032 (  6.88%)
pleural_effusion_mean_area                      1032 (  6.88%)
pleural_effusion_mean_width                     1032 (  6.88%)
pleural_effusion_mean_height                    1032 (  6.88%)
pleural_effusion_mean_x                         1032 (  6.88%)
pleural_effusion_mean_y                         1032 (  6.88%)
calcification_present                            452 (  3.01%)
calcification_agreement                          452 (  3.01%)
calcification_mean_area                          452 (  3.01%)
calcification_mean_width                         452 (  3.01%)
calcification_mean_height                        452 (  3.01%)
calcification_mean_x                             452 (  3.01%)
calcification_mean_y                             452 (  3.01%)
consolidation_present                            353 (  2.35%)
consolidation_agreement                          353 (  2.35%)
consolidation_mean_area                          353 (  2.35%)
consolidation_mean_width                         353 (  2.35%)
consolidation_mean_height                        353 (  2.35%)
consolidation_mean_x                             353 (  2.35%)
consolidation_mean_y                             353 (  2.35%)
pneumothorax_present                              96 (  0.64%)
pneumothorax_agreement                            96 (  0.64%)
pneumothorax_mean_area                            96 (  0.64%)
pneumothorax_mean_width                           96 (  0.64%)
pneumothorax_mean_height                          96 (  0.64%)
pneumothorax_mean_x                               96 (  0.64%)
pneumothorax_mean_y                               96 (  0.64%)

In [42]:
import pandas as pd
import numpy as np

# Load candidate matrix
FEATURE_PATH = "/kaggle/working/conan_imaging_candidate_features.csv"
df = pd.read_csv(FEATURE_PATH)

metadata_cols = [
    "image_id",
    "height",
    "width",
    "photometric"
]

predictor_cols = [
    c for c in df.columns
    if c not in metadata_cols
]

X = df[predictor_cols].copy()

print("=" * 70)
print("CONAN — IMAGING FEATURE REDUNDANCY ANALYSIS")
print("=" * 70)

# ------------------------------------------------------------
# 1. Correlation matrix
# ------------------------------------------------------------

corr = X.corr().abs()

# Ignore self-correlation
np.fill_diagonal(corr.values, 0)

# Find highly correlated pairs
threshold = 0.90

high_corr_pairs = []

for i in range(len(corr.columns)):
    for j in range(i + 1, len(corr.columns)):

        value = corr.iloc[i, j]

        if value >= threshold:
            high_corr_pairs.append({
                "feature_1": corr.columns[i],
                "feature_2": corr.columns[j],
                "abs_correlation": value
            })

high_corr = pd.DataFrame(high_corr_pairs)

if len(high_corr) > 0:
    high_corr = high_corr.sort_values(
        "abs_correlation",
        ascending=False
    )

print("\nHighly correlated pairs (|r| >= 0.90):")
print("Count:", len(high_corr))

if len(high_corr) > 0:
    display(high_corr.head(50))
else:
    print("No highly correlated pairs found.")

# ------------------------------------------------------------
# 2. Feature variance
# ------------------------------------------------------------

variance = X.var().sort_values()

print("\nLowest-variance predictors:")
display(
    variance.head(20).to_frame("variance")
)

# ------------------------------------------------------------
# 3. Number of unique values
# ------------------------------------------------------------

unique_counts = X.nunique().sort_values()

print("\nPredictors with the fewest unique values:")
display(
    unique_counts.head(30).to_frame("unique_values")
)

# ------------------------------------------------------------
# 4. Summary
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SUMMARY")
print("=" * 70)

print("Total predictors:", len(predictor_cols))
print("Highly correlated pairs:", len(high_corr))
print("Minimum variance:", variance.min())
print("Maximum variance:", variance.max())

======================================================================
CONAN — IMAGING FEATURE REDUNDANCY ANALYSIS
======================================================================

Highly correlated pairs (|r| >= 0.90):
Count: 94

,feature_1,feature_2,abs_correlation
3,aortic_enlargement_present,aortic_enlargement_mean_x,0.997599
20,cardiomegaly_present,cardiomegaly_mean_x,0.997305
21,cardiomegaly_present,cardiomegaly_mean_y,0.990521
18,cardiomegaly_present,cardiomegaly_mean_width,0.990407
34,cardiomegaly_mean_x,cardiomegaly_mean_y,0.989375
30,cardiomegaly_mean_width,cardiomegaly_mean_x,0.989115
26,cardiomegaly_mean_area,cardiomegaly_mean_height,0.989080
31,cardiomegaly_mean_width,cardiomegaly_mean_y,0.987803
4,aortic_enlargement_present,aortic_enlargement_mean_y,0.984868
15,aortic_enlargement_mean_x,aortic_enlargement_mean_y,0.982391
74,pleural_effusion_present,pleural_effusion_mean_y,0.980014
39,ild_present,ild_mean_y,0.977458
93,pneumothorax_mean_area,pneumothorax_mean_height,0.976785
10,aortic_enlargement_mean_width,aortic_enlargement_mean_height,0.975692
71,infiltration_mean_area,infiltration_mean_height,0.963394
29,cardiomegaly_mean_width,cardiomegaly_mean_height,0.962650
2,aortic_enlargement_present,aortic_enlargement_mean_height,0.962123
14,aortic_enlargement_mean_height,aortic_enlargement_mean_y,0.960893
13,aortic_enlargement_mean_height,aortic_enlargement_mean_x,0.960836
86,consolidation_mean_area,consolidation_mean_height,0.960301
84,consolidation_present,consolidation_mean_y,0.959954
33,cardiomegaly_mean_height,cardiomegaly_mean_y,0.958124
32,cardiomegaly_mean_height,cardiomegaly_mean_x,0.955524
19,cardiomegaly_present,cardiomegaly_mean_height,0.954566
1,aortic_enlargement_present,aortic_enlargement_mean_width,0.953223
38,ild_present,ild_mean_x,0.952406
41,ild_mean_area,ild_mean_height,0.952211
42,ild_mean_width,ild_mean_height,0.950150
12,aortic_enlargement_mean_width,aortic_enlargement_mean_y,0.950076
25,cardiomegaly_mean_area,cardiomegaly_mean_width,0.950064
11,aortic_enlargement_mean_width,aortic_enlargement_mean_x,0.949182
75,pleural_effusion_mean_area,pleural_effusion_mean_height,0.948431
36,ild_present,ild_mean_width,0.948349
49,nodule_mass_mean_width,nodule_mass_mean_height,0.947888
70,infiltration_present,infiltration_mean_y,0.946344
48,nodule_mass_present,nodule_mass_mean_y,0.945590
8,aortic_enlargement_mean_area,aortic_enlargement_mean_width,0.943569
57,lung_opacity_present,lung_opacity_mean_y,0.942516
64,atelectasis_mean_area,atelectasis_mean_height,0.941889
53,pulmonary_fibrosis_mean_area,pulmonary_fibrosis_mean_height,0.941838
72,infiltration_mean_width,infiltration_mean_height,0.940418
22,cardiomegaly_agreement,cardiomegaly_mean_width,0.939702
16,cardiomegaly_present,cardiomegaly_agreement,0.937298
87,consolidation_mean_width,consolidation_mean_height,0.937274
68,infiltration_present,infiltration_mean_width,0.936739
23,cardiomegaly_agreement,cardiomegaly_mean_x,0.936734
91,pneumothorax_present,pneumothorax_mean_y,0.936247
82,consolidation_present,consolidation_mean_width,0.934924
79,calcification_present,calcification_mean_y,0.933786
67,other_lesion_present,other_lesion_mean_y,0.933030

Lowest-variance predictors:

                              variance
calcification_mean_area       0.000014
pleural_thickening_mean_area  0.000025
nodule_mass_mean_area         0.000026
aortic_enlargement_mean_area  0.000058
atelectasis_mean_area         0.000067
consolidation_mean_area       0.000068
pulmonary_fibrosis_mean_area  0.000081
pneumothorax_mean_area        0.000087
infiltration_mean_area        0.000109
lung_opacity_mean_area        0.000197
other_lesion_mean_area        0.000229
ild_mean_area                 0.000233
pleural_effusion_mean_area    0.000241
calcification_mean_width      0.000267
calcification_mean_height     0.000378
pneumothorax_mean_width       0.000437
nodule_mass_mean_width        0.000505
nodule_mass_mean_height       0.000570
cardiomegaly_mean_area        0.000586
atelectasis_mean_width        0.000616

Predictors with the fewest unique values:

                              unique_values
aortic_enlargement_present                2
cardiomegaly_present                      2
pleural_thickening_present                2
ild_present                               2
nodule_mass_present                       2
other_lesion_present                      2
lung_opacity_present                      2
pulmonary_fibrosis_present                2
atelectasis_present                       2
infiltration_present                      2
calcification_present                     2
pleural_effusion_present                  2
consolidation_present                     2
pneumothorax_present                      2
atelectasis_agreement                     4
nodule_mass_agreement                     4
pulmonary_fibrosis_agreement              4
lung_opacity_agreement                    4
other_lesion_agreement                    4
calcification_agreement                   4
ild_agreement                             4
pleural_thickening_agreement              4
cardiomegaly_agreement                    4
consolidation_agreement                   4
infiltration_agreement                    4
pleural_effusion_agreement                4
pneumothorax_agreement                    4
aortic_enlargement_agreement              4
pneumothorax_mean_width                  96
pneumothorax_mean_area                   97

======================================================================
SUMMARY
======================================================================
Total predictors: 98
Highly correlated pairs: 94
Minimum variance: 1.4220344300735074e-05
Maximum variance: 0.16267089361512552

In [44]:
import pandas as pd
import numpy as np

print("=" * 70)
print("CONAN — REDUCED IMAGING FEATURE SET")
print("=" * 70)

# ============================================================
# 1. LOCATE THE EXISTING CANDIDATE FEATURE MATRIX
# ============================================================

candidate_path = "/kaggle/working/conan_imaging_candidate_features.csv"

df = pd.read_csv(candidate_path)

print("\nLoaded:")
print(candidate_path)

print("\nOriginal dataset shape:")
print(df.shape)


# ============================================================
# 2. DEFINE THE 14 RADIOGRAPHIC ABNORMALITIES
# ============================================================

abnormalities = [
    "aortic_enlargement",
    "cardiomegaly",
    "pleural_thickening",
    "ild",
    "nodule_mass",
    "pulmonary_fibrosis",
    "lung_opacity",
    "atelectasis",
    "other_lesion",
    "infiltration",
    "pleural_effusion",
    "calcification",
    "consolidation",
    "pneumothorax"
]


# ============================================================
# 3. SELECT REDUCED PREDICTORS
# ============================================================

selected_features = []

for abnormality in abnormalities:

    selected_features.extend([
        f"{abnormality}_present",
        f"{abnormality}_agreement",
        f"{abnormality}_mean_area"
    ])


# ============================================================
# 4. METADATA
# ============================================================

metadata = [
    "image_id",
    "height",
    "width",
    "photometric"
]


# ============================================================
# 5. VERIFY REQUIRED COLUMNS
# ============================================================

required_columns = metadata + selected_features

missing_columns = [
    col for col in required_columns
    if col not in df.columns
]

if missing_columns:

    print("\nERROR — Missing columns:")
    
    for col in missing_columns:
        print(" -", col)

    raise ValueError(
        f"{len(missing_columns)} required columns are missing."
    )


# ============================================================
# 6. CREATE REDUCED MATRIX
# ============================================================

reduced_df = df[required_columns].copy()


# ============================================================
# 7. BASIC VALIDATION
# ============================================================

print("\n" + "=" * 70)
print("REDUCED FEATURE MATRIX")
print("=" * 70)

print("\nRows:")
print(len(reduced_df))

print("\nMetadata columns:")
print(len(metadata))

print("\nPredictor columns:")
print(len(selected_features))

print("\nTotal columns:")
print(len(reduced_df.columns))

print("\nShape:")
print(reduced_df.shape)

print("\nMissing values:")
print(
    reduced_df[selected_features]
    .isnull()
    .sum()
    .sum()
)

print("\nDuplicate image IDs:")
print(
    reduced_df["image_id"]
    .duplicated()
    .sum()
)


# ============================================================
# 8. CHECK THAT EACH IMAGE OCCURS ONCE
# ============================================================

unique_images = reduced_df["image_id"].nunique()

print("\nUnique images:")
print(unique_images)

if unique_images != len(reduced_df):

    print("\nWARNING:")
    print("Some image IDs occur more than once.")

else:

    print("\n✓ One row per image confirmed.")


# ============================================================
# 9. SHOW SELECTED PREDICTORS
# ============================================================

print("\n" + "=" * 70)
print("SELECTED IMAGING PREDICTORS")
print("=" * 70)

for i, feature in enumerate(selected_features, 1):
    print(f"{i:02d}. {feature}")


# ============================================================
# 10. CHECK PREDICTOR TYPES
# ============================================================

print("\n" + "=" * 70)
print("PREDICTOR TYPES")
print("=" * 70)

print(
    reduced_df[selected_features]
    .dtypes
    .value_counts()
)


# ============================================================
# 11. SAVE
# ============================================================

output_path = "/kaggle/working/conan_imaging_reduced_features.csv"

reduced_df.to_csv(
    output_path,
    index=False
)

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(output_path)


# ============================================================
# 12. PREVIEW
# ============================================================

print("\nFirst 5 rows:")

display(
    reduced_df.head()
)

======================================================================
CONAN — REDUCED IMAGING FEATURE SET
======================================================================

Loaded:
/kaggle/working/conan_imaging_candidate_features.csv

Original dataset shape:
(15000, 102)

======================================================================
REDUCED FEATURE MATRIX
======================================================================

Rows:
15000

Metadata columns:
4

Predictor columns:
42

Total columns:
46

Shape:
(15000, 46)

Missing values:
0

Duplicate image IDs:
0

Unique images:
15000

✓ One row per image confirmed.

======================================================================
SELECTED IMAGING PREDICTORS
======================================================================
01. aortic_enlargement_present
02. aortic_enlargement_agreement
03. aortic_enlargement_mean_area
04. cardiomegaly_present
05. cardiomegaly_agreement
06. cardiomegaly_mean_area
07. pleural_thickening_present
08. pleural_thickening_agreement
09. pleural_thickening_mean_area
10. ild_present
11. ild_agreement
12. ild_mean_area
13. nodule_mass_present
14. nodule_mass_agreement
15. nodule_mass_mean_area
16. pulmonary_fibrosis_present
17. pulmonary_fibrosis_agreement
18. pulmonary_fibrosis_mean_area
19. lung_opacity_present
20. lung_opacity_agreement
21. lung_opacity_mean_area
22. atelectasis_present
23. atelectasis_agreement
24. atelectasis_mean_area
25. other_lesion_present
26. other_lesion_agreement
27. other_lesion_mean_area
28. infiltration_present
29. infiltration_agreement
30. infiltration_mean_area
31. pleural_effusion_present
32. pleural_effusion_agreement
33. pleural_effusion_mean_area
34. calcification_present
35. calcification_agreement
36. calcification_mean_area
37. consolidation_present
38. consolidation_agreement
39. consolidation_mean_area
40. pneumothorax_present
41. pneumothorax_agreement
42. pneumothorax_mean_area

======================================================================
PREDICTOR TYPES
======================================================================
float64    42
Name: count, dtype: int64

======================================================================
SAVED
======================================================================
/kaggle/working/conan_imaging_reduced_features.csv

First 5 rows:

,image_id,height,width,photometric,aortic_enlargement_present,aortic_enlargement_agreement,aortic_enlargement_mean_area,cardiomegaly_present,cardiomegaly_agreement,cardiomegaly_mean_area,...,pleural_effusion_mean_area,calcification_present,calcification_agreement,calcification_mean_area,consolidation_present,consolidation_agreement,consolidation_mean_area,pneumothorax_present,pneumothorax_agreement,pneumothorax_mean_area
0,50a418190bc3fb1ef1633bf9678929b3,2580,2332,MONOCHROME2,0.0,0.000000,0.000000,0.0,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,21a10246a5ec7af151081d0cd6d65dc9,3159,2954,MONOCHROME2,0.0,0.000000,0.000000,0.0,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,9a5094b2563a1ef3ff50dc5c7ff71345,2336,2080,MONOCHROME1,1.0,0.333333,0.012760,1.0,1.0,0.088325,...,0.004655,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,051132a778e61a86eb147c7c6f564dfe,2880,2304,MONOCHROME1,1.0,1.000000,0.015699,1.0,1.0,0.060525,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,063319de25ce7edb9b1c6b8881290140,3072,2540,MONOCHROME2,0.0,0.000000,0.000000,0.0,0.0,0.000000,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [45]:
# ================================================================
# CONAN — IMAGING TARGET PREPARATION
# ================================================================

import os
import pandas as pd
import numpy as np

print("=" * 70)
print("CONAN — IMAGING TARGET PREPARATION")
print("=" * 70)

# ------------------------------------------------
# 1. Load reduced VinBigData feature matrix
# ------------------------------------------------

FEATURE_PATH = "/kaggle/working/conan_imaging_reduced_features.csv"

if not os.path.exists(FEATURE_PATH):
    raise FileNotFoundError(
        f"Feature matrix not found:\n{FEATURE_PATH}"
    )

df = pd.read_csv(FEATURE_PATH)

print("\nLoaded:")
print(FEATURE_PATH)

print("\nDataset shape:")
print(df.shape)

print("\nColumns:")
print(df.columns.tolist())

# ------------------------------------------------
# 2. Basic validation
# ------------------------------------------------

required_metadata = [
    "image_id",
    "height",
    "width",
    "photometric"
]

missing_metadata = [
    c for c in required_metadata
    if c not in df.columns
]

if missing_metadata:
    raise ValueError(
        f"Missing metadata columns: {missing_metadata}"
    )

print("\nMetadata validation:")
print("✓ image_id")
print("✓ height")
print("✓ width")
print("✓ photometric")

# ------------------------------------------------
# 3. Check image IDs
# ------------------------------------------------

print("\nImage ID validation")

print("Total rows:", len(df))
print("Unique image IDs:", df["image_id"].nunique())
print("Duplicate IDs:", df["image_id"].duplicated().sum())

assert df["image_id"].nunique() == len(df)

print("✓ One row per image")

# ------------------------------------------------
# 4. Check target-like abnormalities
# ------------------------------------------------

print("\nNodule/Mass radiographic evidence")

if "nodule_mass_present" in df.columns:

    nodule_count = int(
        df["nodule_mass_present"].sum()
    )

    total = len(df)

    print(
        f"Nodule/Mass positive: {nodule_count:,} "
        f"({100*nodule_count/total:.2f}%)"
    )

    print(
        f"Nodule/Mass negative: {total-nodule_count:,} "
        f"({100*(total-nodule_count)/total:.2f}%)"
    )

print("\nIMPORTANT:")
print("nodule_mass_present is NOT being used as a lung-cancer label.")
print("It is treated as radiographic evidence only.")

# ------------------------------------------------
# 5. Check candidate target columns
# ------------------------------------------------

possible_targets = [
    "lung_cancer",
    "LUNG_CANCER",
    "cancer",
    "Cancer",
    "diagnosis",
    "Diagnosis",
    "risk_label"
]

found_targets = [
    c for c in possible_targets
    if c in df.columns
]

print("\nPossible cancer target columns:")
print(found_targets)

if not found_targets:

    print("\n✓ No cancer target is embedded in VinBigData.")
    print("\nThis is expected.")
    print("A separate cancer-labeled dataset is required.")

# ------------------------------------------------
# 6. Save validated feature matrix
# ------------------------------------------------

OUTPUT = "/kaggle/working/conan_imaging_features_validated.csv"

df.to_csv(
    OUTPUT,
    index=False
)

print("\n" + "=" * 70)
print("VALIDATED FEATURE MATRIX SAVED")
print("=" * 70)

print(OUTPUT)
print("Shape:", df.shape)

# ------------------------------------------------
# 7. Final architecture reminder
# ------------------------------------------------

print("\n" + "=" * 70)
print("CONAN IMAGING PIPELINE")
print("=" * 70)

print("""
VinBigData
    ↓
14 radiographic abnormalities
    ↓
98 candidate predictors
    ↓
redundancy / variance analysis
    ↓
42 reduced predictors
    ↓
15,000-image radiographic feature matrix
    ↓
        ┌─────────────────────────────┐
        │                              │
        │  Separate cancer-labeled    │
        │  dataset (JSRT / cancer)    │
        │                              │
        └──────────────┬──────────────┘
                       ↓
             Lung-cancer target
                       ↓
              Imaging risk model
                       ↓
          P(lung cancer | X-ray)
""")

======================================================================
CONAN — IMAGING TARGET PREPARATION
======================================================================

Loaded:
/kaggle/working/conan_imaging_reduced_features.csv

Dataset shape:
(15000, 46)

Columns:
['image_id', 'height', 'width', 'photometric', 'aortic_enlargement_present', 'aortic_enlargement_agreement', 'aortic_enlargement_mean_area', 'cardiomegaly_present', 'cardiomegaly_agreement', 'cardiomegaly_mean_area', 'pleural_thickening_present', 'pleural_thickening_agreement', 'pleural_thickening_mean_area', 'ild_present', 'ild_agreement', 'ild_mean_area', 'nodule_mass_present', 'nodule_mass_agreement', 'nodule_mass_mean_area', 'pulmonary_fibrosis_present', 'pulmonary_fibrosis_agreement', 'pulmonary_fibrosis_mean_area', 'lung_opacity_present', 'lung_opacity_agreement', 'lung_opacity_mean_area', 'atelectasis_present', 'atelectasis_agreement', 'atelectasis_mean_area', 'other_lesion_present', 'other_lesion_agreement', 'other_lesion_mean_area', 'infiltration_present', 'infiltration_agreement', 'infiltration_mean_area', 'pleural_effusion_present', 'pleural_effusion_agreement', 'pleural_effusion_mean_area', 'calcification_present', 'calcification_agreement', 'calcification_mean_area', 'consolidation_present', 'consolidation_agreement', 'consolidation_mean_area', 'pneumothorax_present', 'pneumothorax_agreement', 'pneumothorax_mean_area']

Metadata validation:
✓ image_id
✓ height
✓ width
✓ photometric

Image ID validation
Total rows: 15000
Unique image IDs: 15000
Duplicate IDs: 0
✓ One row per image

Nodule/Mass radiographic evidence
Nodule/Mass positive: 826 (5.51%)
Nodule/Mass negative: 14,174 (94.49%)

IMPORTANT:
nodule_mass_present is NOT being used as a lung-cancer label.
It is treated as radiographic evidence only.

Possible cancer target columns:
[]

✓ No cancer target is embedded in VinBigData.

This is expected.
A separate cancer-labeled dataset is required.

======================================================================
VALIDATED FEATURE MATRIX SAVED
======================================================================
/kaggle/working/conan_imaging_features_validated.csv
Shape: (15000, 46)

======================================================================
CONAN IMAGING PIPELINE
======================================================================

VinBigData
    ↓
14 radiographic abnormalities
    ↓
98 candidate predictors
    ↓
redundancy / variance analysis
    ↓
42 reduced predictors
    ↓
15,000-image radiographic feature matrix
    ↓
        ┌─────────────────────────────┐
        │                              │
        │  Separate cancer-labeled    │
        │  dataset (JSRT / cancer)    │
        │                              │
        └──────────────┬──────────────┘
                       ↓
             Lung-cancer target
                       ↓
              Imaging risk model
                       ↓
          P(lung cancer | X-ray)

In [46]:
# ================================================================
# CONAN — SEARCH FOR CANCER-LABELED IMAGING DATA
# ================================================================

import os
import glob
import pandas as pd

print("=" * 70)
print("CONAN — SEARCHING FOR CANCER-LABELED IMAGING DATA")
print("=" * 70)

search_roots = [
    "/kaggle/input",
    "/kaggle/working"
]

# ------------------------------------------------
# 1. Search filenames
# ------------------------------------------------

keywords = [
    "jsrt",
    "cancer",
    "lung",
    "diagnosis",
    "metadata",
    "nodule"
]

matches = []

for root in search_roots:
    for dirpath, dirnames, filenames in os.walk(root):

        for filename in filenames:

            lower = filename.lower()

            if any(k in lower for k in keywords):

                matches.append(
                    os.path.join(dirpath, filename)
                )

print("\nPotentially relevant files:")
print("-" * 70)

if matches:
    for path in sorted(matches):
        print(path)
else:
    print("NONE FOUND")

# ------------------------------------------------
# 2. Search directories
# ------------------------------------------------

print("\n" + "=" * 70)
print("RELEVANT DIRECTORIES")
print("=" * 70)

directory_matches = []

for root in search_roots:
    for dirpath, dirnames, filenames in os.walk(root):

        lower_path = dirpath.lower()

        if any(k in lower_path for k in keywords):

            directory_matches.append(dirpath)

for path in sorted(set(directory_matches)):
    print(path)

# ------------------------------------------------
# 3. Look specifically for CSV files
# ------------------------------------------------

print("\n" + "=" * 70)
print("CSV FILES WITH POSSIBLE LABEL INFORMATION")
print("=" * 70)

csv_files = []

for root in search_roots:
    csv_files.extend(
        glob.glob(
            os.path.join(root, "**", "*.csv"),
            recursive=True
        )
    )

for path in sorted(set(csv_files)):

    filename = os.path.basename(path).lower()

    if any(
        k in filename
        for k in [
            "jsrt",
            "cancer",
            "lung",
            "diagnosis",
            "metadata",
            "label"
        ]
    ):

        print(path)

# ------------------------------------------------
# 4. Search for known JSRT metadata columns
# ------------------------------------------------

print("\n" + "=" * 70)
print("SEARCHING CSV CONTENT")
print("=" * 70)

known_jsrt_columns = {
    "study_id",
    "subtlety",
    "size",
    "age",
    "gender",
    "x",
    "y",
    "state",
    "position",
    "diagnosis"
}

for path in sorted(set(csv_files)):

    try:
        sample = pd.read_csv(
            path,
            nrows=5
        )

        cols = set(sample.columns)

        overlap = cols.intersection(
            known_jsrt_columns
        )

        if len(overlap) >= 3:

            print("\nPOSSIBLE JSRT FILE:")
            print(path)

            print("Columns:")
            print(sample.columns.tolist())

            print(
                "Matching JSRT columns:",
                sorted(overlap)
            )

    except Exception:
        pass

print("\n" + "=" * 70)
print("SEARCH COMPLETE")
print("=" * 70)

======================================================================
CONAN — SEARCHING FOR CANCER-LABELED IMAGING DATA
======================================================================

Potentially relevant files:
----------------------------------------------------------------------
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv

======================================================================
RELEVANT DIRECTORIES
======================================================================
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/images
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/images/images

======================================================================
CSV FILES WITH POSSIBLE LABEL INFORMATION
======================================================================
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv

======================================================================
SEARCHING CSV CONTENT
======================================================================

POSSIBLE JSRT FILE:
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv
Columns:
['study_id', 'subtlety', 'size', 'age', 'gender', 'x', 'y', 'state', 'position', 'diagnosis']
Matching JSRT columns: ['age', 'diagnosis', 'gender', 'position', 'size', 'state', 'study_id', 'subtlety', 'x', 'y']

======================================================================
SEARCH COMPLETE
======================================================================

In [47]:
import os

print("=" * 70)
print("CONAN — CHECKING AVAILABLE KAGGLE DATASETS")
print("=" * 70)

for root, dirs, files in os.walk("/kaggle/input"):

    # Only show top-level dataset folders
    depth = root.replace("/kaggle/input", "").count(os.sep)

    if depth <= 1:
        print(root)

print("\n" + "=" * 70)
print("DATASET FOLDERS")
print("=" * 70)

for item in sorted(os.listdir("/kaggle/input")):
    path = os.path.join("/kaggle/input", item)

    if os.path.isdir(path):
        print("📁", item)

======================================================================
CONAN — CHECKING AVAILABLE KAGGLE DATASETS
======================================================================
/kaggle/input
/kaggle/input/competitions
/kaggle/input/datasets

======================================================================
DATASET FOLDERS
======================================================================
📁 competitions
📁 datasets

In [48]:
# ================================================================
# CONAN — JSRT LUNG CANCER TARGET CONSTRUCTION
# ================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("CONAN — JSRT LUNG CANCER TARGET CONSTRUCTION")
print("=" * 70)

# ------------------------------------------------
# Load JSRT metadata
# ------------------------------------------------

JSRT_PATH = "/kaggle/input/jsrt-metadata/jsrt_metadata.csv"

# If your Kaggle path is different, automatically locate it
import os
import glob

if not os.path.exists(JSRT_PATH):

    candidates = glob.glob(
        "/kaggle/input/**/*.csv",
        recursive=True
    )

    jsrt_candidates = []

    for path in candidates:

        try:
            temp = pd.read_csv(path, nrows=5)

            required = {
                "study_id",
                "subtlety",
                "size",
                "age",
                "gender",
                "x",
                "y",
                "state",
                "position",
                "diagnosis"
            }

            if required.issubset(set(temp.columns)):
                jsrt_candidates.append(path)

        except Exception:
            pass

    if len(jsrt_candidates) == 0:
        raise FileNotFoundError(
            "Could not locate JSRT metadata."
        )

    JSRT_PATH = jsrt_candidates[0]

print("\nUsing:")
print(JSRT_PATH)

jsrt = pd.read_csv(JSRT_PATH)

print("\nOriginal shape:")
print(jsrt.shape)

# ------------------------------------------------
# Validate columns
# ------------------------------------------------

required_columns = [
    "study_id",
    "subtlety",
    "size",
    "age",
    "gender",
    "x",
    "y",
    "state",
    "position",
    "diagnosis"
]

missing = [
    c for c in required_columns
    if c not in jsrt.columns
]

if missing:
    raise ValueError(
        f"Missing columns: {missing}"
    )

print("\n✓ Required JSRT columns confirmed")

# ------------------------------------------------
# Inspect state
# ------------------------------------------------

print("\n" + "=" * 70)
print("JSRT STATE DISTRIBUTION")
print("=" * 70)

print(
    jsrt["state"]
    .value_counts(dropna=False)
)

print("\nPercentages:")
print(
    (jsrt["state"].value_counts(normalize=True) * 100)
    .round(2)
)

# ------------------------------------------------
# Inspect diagnosis
# ------------------------------------------------

print("\n" + "=" * 70)
print("JSRT DIAGNOSIS DISTRIBUTION")
print("=" * 70)

print(
    jsrt["diagnosis"]
    .value_counts(dropna=False)
)

# ------------------------------------------------
# Construct cancer target
# ------------------------------------------------

jsrt["lung_cancer"] = (
    jsrt["state"]
    .astype(str)
    .str.strip()
    .str.lower()
    .eq("malignant")
    .astype(int)
)

# ------------------------------------------------
# Validate target
# ------------------------------------------------

print("\n" + "=" * 70)
print("LUNG CANCER TARGET")
print("=" * 70)

print(
    jsrt["lung_cancer"]
    .value_counts()
    .sort_index()
)

print("\nTarget percentages:")

target_pct = (
    jsrt["lung_cancer"]
    .value_counts(normalize=True)
    .sort_index() * 100
)

print(target_pct.round(2))

# ------------------------------------------------
# Check state ↔ target consistency
# ------------------------------------------------

print("\n" + "=" * 70)
print("TARGET VALIDATION")
print("=" * 70)

validation = pd.crosstab(
    jsrt["state"],
    jsrt["lung_cancer"]
)

print(validation)

# ------------------------------------------------
# Missing values
# ------------------------------------------------

print("\n" + "=" * 70)
print("MISSING VALUES")
print("=" * 70)

print(
    jsrt[required_columns + ["lung_cancer"]]
    .isna()
    .sum()
)

# ------------------------------------------------
# Duplicate studies
# ------------------------------------------------

print("\n" + "=" * 70)
print("IMAGE ID VALIDATION")
print("=" * 70)

print("Rows:", len(jsrt))
print(
    "Unique study IDs:",
    jsrt["study_id"].nunique()
)

print(
    "Duplicate study IDs:",
    jsrt["study_id"].duplicated().sum()
)

# ------------------------------------------------
# Save target dataset
# ------------------------------------------------

OUTPUT = "/kaggle/working/conan_jsrt_cancer_target.csv"

jsrt.to_csv(
    OUTPUT,
    index=False
)

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(OUTPUT)
print("Shape:", jsrt.shape)

print("\nFirst 10 cases:")
print(
    jsrt[
        [
            "study_id",
            "age",
            "gender",
            "size",
            "state",
            "diagnosis",
            "lung_cancer"
        ]
    ].head(10).to_string(index=False)
)

======================================================================
CONAN — JSRT LUNG CANCER TARGET CONSTRUCTION
======================================================================

Using:
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv

Original shape:
(247, 10)

✓ Required JSRT columns confirmed

======================================================================
JSRT STATE DISTRIBUTION
======================================================================
state
malignant     100
non-nodule     93
benign         54
Name: count, dtype: int64

Percentages:
state
malignant     40.49
non-nodule    37.65
benign        21.86
Name: proportion, dtype: float64

======================================================================
JSRT DIAGNOSIS DISTRIBUTION
======================================================================
diagnosis
NaN                                               93
lung cancer                                       56
lung cancer(adenocarcinoma)                       23
tuberculoma                                       14
granuloma                                          8
lung cancer(bronchioloalveolar cell carcinoma)     7
metastasis of colon cancer                         4
unknown                                            4
inflammatory mass                                  4
pulmonary tuberculosis                             3
lung abscess                                       2
Inflammatory mass                                  2
hamartoma                                          2
Cryptococcosis                                     2
lung cancer(squamous cell carcinoma)               2
susp. inflammatory mass                            2
pulmonary hematoma                                 2
sclerosing hemangioma                              2
susp. sclerosing hemangioma                        1
organiging pneumonia                               1
susp.tuberculoma                                   1
lung cancer(adenosquamous carcinoma)               1
calcified granuloma                                1
lung cancer(small cell carcinoma)                  1
lung canceror metastasis                           1
lung cancer(large cell carcinoma)                  1
pneumonia                                          1
metastasis of ovarian cancer                       1
metastatic lung cancer                             1
organizing pneumonia                               1
metastasis of uterine cancer                       1
susp. hamartoma                                    1
susp. lung metastasis                              1
Name: count, dtype: int64

======================================================================
LUNG CANCER TARGET
======================================================================
lung_cancer
0    147
1    100
Name: count, dtype: int64

Target percentages:
lung_cancer
0    59.51
1    40.49
Name: proportion, dtype: float64

======================================================================
TARGET VALIDATION
======================================================================
lung_cancer   0    1
state
benign       54    0
malignant     0  100
non-nodule   93    0

======================================================================
MISSING VALUES
======================================================================
study_id        0
subtlety       93
size           93
age             0
gender          0
x              93
y              93
state           0
position       93
diagnosis      93
lung_cancer     0
dtype: int64

======================================================================
IMAGE ID VALIDATION
======================================================================
Rows: 247
Unique study IDs: 247
Duplicate study IDs: 0

======================================================================
SAVED
======================================================================
/kaggle/working/conan_jsrt_cancer_target.csv
Shape: (247, 11)

First 10 cases:
    study_id age gender  size     state          diagnosis  lung_cancer
JPCLN001.png  53   Male  15.0 malignant        lung cancer            1
JPCLN002.png  78 Female  30.0    benign pulmonary hematoma            0
JPCLN003.png  63 Female  30.0 malignant        lung cancer            1
JPCLN004.png  68 Female  14.0    benign  Inflammatory mass            0
JPCLN005.png  73 Female  35.0 malignant        lung cancer            1
JPCLN006.png  64 Female  14.0    benign        tuberculoma            0
JPCLN007.png  69   Male  18.0 malignant        lung cancer            1
JPCLN008.png  44 Female  10.0    benign          granuloma            0
JPCLN009.png  61 Female  28.0 malignant        lung cancer            1
JPCLN010.png  60 Female  25.0 malignant        lung cancer            1

In [49]:
import os

print("=" * 70)
print("SEARCHING KAGGLE INPUT FOR JSRT METADATA")
print("=" * 70)

matches = []

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file.lower() == "jsrt_metadata.csv":
            matches.append(os.path.join(root, file))

print("\nMatches found:")
for path in matches:
    print(path)

if not matches:
    print("\n❌ jsrt_metadata.csv is NOT mounted in this notebook.")
    print("\nAvailable datasets:")
    for item in os.listdir("/kaggle/input"):
        print(" -", item)
else:
    print("\n✓ JSRT metadata found!")

======================================================================
SEARCHING KAGGLE INPUT FOR JSRT METADATA
======================================================================

Matches found:
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv

✓ JSRT metadata found!

In [50]:
import os

print("=" * 70)
print("SEARCHING FOR JSRT METADATA")
print("=" * 70)

matches = []

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file.lower() == "jsrt_metadata.csv":
            matches.append(os.path.join(root, file))

print("\nFound:", len(matches))

for path in matches:
    print(path)

======================================================================
SEARCHING FOR JSRT METADATA
======================================================================

Found: 1
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv

In [52]:
import pandas as pd
import os

print("=" * 70)
print("CONAN — JSRT METADATA INSPECTION")
print("=" * 70)

# Find jsrt_metadata.csv automatically
jsrt_candidates = []

for root, dirs, files in os.walk("/kaggle/input"):
    for file in files:
        if file.lower() == "jsrt_metadata.csv":
            jsrt_candidates.append(os.path.join(root, file))

if len(jsrt_candidates) == 0:
    raise FileNotFoundError(
        "jsrt_metadata.csv was not found. "
        "Please add the raddar JSRT dataset to Kaggle Inputs."
    )

jsrt_path = jsrt_candidates[0]

print("\nJSRT metadata found:")
print(jsrt_path)

# Load
jsrt = pd.read_csv(jsrt_path)

print("\n" + "=" * 70)
print("JSRT DATASET")
print("=" * 70)

print("Shape:", jsrt.shape)

print("\nColumns:")
for i, col in enumerate(jsrt.columns, 1):
    print(f"{i:02d}. {col}")

print("\nFirst 5 rows:")
display(jsrt.head())

print("\nData types:")
print(jsrt.dtypes)

print("\nMissing values:")
print(jsrt.isna().sum())

======================================================================
CONAN — JSRT METADATA INSPECTION
======================================================================

JSRT metadata found:
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv

======================================================================
JSRT DATASET
======================================================================
Shape: (247, 10)

Columns:
01. study_id
02. subtlety
03. size
04. age
05. gender
06. x
07. y
08. state
09. position
10. diagnosis

First 5 rows:

,study_id,subtlety,size,age,gender,x,y,state,position,diagnosis
0,JPCLN001.png,5.0,15.0,53,Male,1634.0,692.0,malignant,l.upper lobe,lung cancer
1,JPCLN002.png,5.0,30.0,78,Female,1614.0,1090.0,benign,l.upper lobe(S5),pulmonary hematoma
2,JPCLN003.png,5.0,30.0,63,Female,1303.0,447.0,malignant,l.upper lobe(S1+2),lung cancer
3,JPCLN004.png,5.0,14.0,68,Female,606.0,836.0,benign,r.upper lobe,Inflammatory mass
4,JPCLN005.png,5.0,35.0,73,Female,1438.0,692.0,malignant,l.upper lobe(S3),lung cancer

Data types:
study_id      object
subtlety     float64
size         float64
age           object
gender        object
x            float64
y            float64
state         object
position      object
diagnosis     object
dtype: object

Missing values:
study_id      0
subtlety     93
size         93
age           0
gender        0
x            93
y            93
state         0
position     93
diagnosis    93
dtype: int64

In [53]:
import pandas as pd
import numpy as np

print("=" * 70)
print("CONAN — JSRT CANCER TARGET ANALYSIS")
print("=" * 70)

# Load JSRT metadata
jsrt = pd.read_csv(
    "/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv"
)

print("\nOriginal JSRT records:", len(jsrt))

# ------------------------------------------------------------
# 1. Examine state
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STATE DISTRIBUTION")
print("=" * 70)

print(jsrt["state"].value_counts(dropna=False))

# ------------------------------------------------------------
# 2. Examine diagnosis
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DIAGNOSIS DISTRIBUTION")
print("=" * 70)

print(jsrt["diagnosis"].value_counts(dropna=False))

# ------------------------------------------------------------
# 3. Identify records usable for cancer target
# ------------------------------------------------------------

target_mask = jsrt["state"].notna()

jsrt_target = jsrt[target_mask].copy()

print("\n" + "=" * 70)
print("USABLE CANCER-LABELED RECORDS")
print("=" * 70)

print("Total records:", len(jsrt))
print("Usable labeled records:", len(jsrt_target))
print("Excluded unlabeled records:", len(jsrt) - len(jsrt_target))

# ------------------------------------------------------------
# 4. Create binary cancer target
# ------------------------------------------------------------

jsrt_target["lung_cancer"] = (
    jsrt_target["state"]
    .astype(str)
    .str.strip()
    .str.lower()
    .map({
        "malignant": 1,
        "benign": 0
    })
)

print("\n" + "=" * 70)
print("LUNG CANCER TARGET")
print("=" * 70)

print(jsrt_target["lung_cancer"].value_counts(dropna=False))

# ------------------------------------------------------------
# 5. Check whether any state values failed mapping
# ------------------------------------------------------------

unmapped = jsrt_target[
    jsrt_target["lung_cancer"].isna()
]

print("\nUnmapped state values:", len(unmapped))

if len(unmapped) > 0:
    print(unmapped["state"].value_counts(dropna=False))

# ------------------------------------------------------------
# 6. Cancer target percentages
# ------------------------------------------------------------

valid_target = jsrt_target["lung_cancer"].notna()

target_counts = (
    jsrt_target.loc[valid_target, "lung_cancer"]
    .value_counts()
    .sort_index()
)

print("\n" + "=" * 70)
print("TARGET DISTRIBUTION")
print("=" * 70)

for label, count in target_counts.items():
    name = "Non-cancer / Benign" if label == 0 else "Lung cancer / Malignant"
    percentage = count / valid_target.sum() * 100
    print(f"{name:25s}: {count:4d} ({percentage:6.2f}%)")

# ------------------------------------------------------------
# 7. Check diagnosis consistency
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STATE × DIAGNOSIS")
print("=" * 70)

print(
    pd.crosstab(
        jsrt_target["state"],
        jsrt_target["diagnosis"],
        dropna=False
    )
)

# ------------------------------------------------------------
# 8. Save preliminary target dataset
# ------------------------------------------------------------

output_path = "/kaggle/working/conan_jsrt_target_prepared.csv"

jsrt_target.to_csv(output_path, index=False)

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(output_path)
print("Shape:", jsrt_target.shape)

======================================================================
CONAN — JSRT CANCER TARGET ANALYSIS
======================================================================

Original JSRT records: 247

======================================================================
STATE DISTRIBUTION
======================================================================
state
malignant     100
non-nodule     93
benign         54
Name: count, dtype: int64

======================================================================
DIAGNOSIS DISTRIBUTION
======================================================================
diagnosis
NaN                                               93
lung cancer                                       56
lung cancer(adenocarcinoma)                       23
tuberculoma                                       14
granuloma                                          8
lung cancer(bronchioloalveolar cell carcinoma)     7
metastasis of colon cancer                         4
unknown                                            4
inflammatory mass                                  4
pulmonary tuberculosis                             3
lung abscess                                       2
Inflammatory mass                                  2
hamartoma                                          2
Cryptococcosis                                     2
lung cancer(squamous cell carcinoma)               2
susp. inflammatory mass                            2
pulmonary hematoma                                 2
sclerosing hemangioma                              2
susp. sclerosing hemangioma                        1
organiging pneumonia                               1
susp.tuberculoma                                   1
lung cancer(adenosquamous carcinoma)               1
calcified granuloma                                1
lung cancer(small cell carcinoma)                  1
lung canceror metastasis                           1
lung cancer(large cell carcinoma)                  1
pneumonia                                          1
metastasis of ovarian cancer                       1
metastatic lung cancer                             1
organizing pneumonia                               1
metastasis of uterine cancer                       1
susp. hamartoma                                    1
susp. lung metastasis                              1
Name: count, dtype: int64

======================================================================
USABLE CANCER-LABELED RECORDS
======================================================================
Total records: 247
Usable labeled records: 247
Excluded unlabeled records: 0

======================================================================
LUNG CANCER TARGET
======================================================================
lung_cancer
1.0    100
NaN     93
0.0     54
Name: count, dtype: int64

Unmapped state values: 93
state
non-nodule    93
Name: count, dtype: int64

======================================================================
TARGET DISTRIBUTION
======================================================================
Non-cancer / Benign      :   54 ( 35.06%)
Lung cancer / Malignant  :  100 ( 64.94%)

======================================================================
STATE × DIAGNOSIS
======================================================================
diagnosis   Cryptococcosis  Inflammatory mass  calcified granuloma  granuloma  \
state
benign                   2                  2                    1          8
malignant                0                  0                    0          0
non-nodule               0                  0                    0          0

diagnosis   hamartoma  inflammatory mass  lung abscess  lung cancer  \
state
benign              2                  4             2            0
malignant           0                  0             0           56
non-nodule          0                  0             0            0

diagnosis   lung cancer(adenocarcinoma)  lung cancer(adenosquamous carcinoma)  \
state
benign                                0                                     0
malignant                            23                                     1
non-nodule                            0                                     0

diagnosis   ...  pulmonary tuberculosis  sclerosing hemangioma  \
state       ...
benign      ...                       3                      2
malignant   ...                       0                      0
non-nodule  ...                       0                      0

diagnosis   susp. hamartoma  susp. inflammatory mass  susp. lung metastasis  \
state
benign                    1                        2                      0
malignant                 0                        0                      1
non-nodule                0                        0                      0

diagnosis   susp. sclerosing hemangioma  susp.tuberculoma  tuberculoma  \
state
benign                                1                 1           14
malignant                             0                 0            0
non-nodule                            0                 0            0

diagnosis   unknown  NaN
state
benign            4    0
malignant         0    0
non-nodule        0   93

[3 rows x 33 columns]

======================================================================
SAVED
======================================================================
/kaggle/working/conan_jsrt_target_prepared.csv
Shape: (247, 11)

In [54]:
# ================================================================
# CONAN — JSRT CANCER DATASET CLEANING + IMAGE VERIFICATION
# ================================================================

import os
import glob
import pandas as pd
import numpy as np

print("=" * 70)
print("CONAN — JSRT CANCER DATASET PREPARATION")
print("=" * 70)

# ------------------------------------------------
# 1. Load JSRT metadata
# ------------------------------------------------

metadata_path = "/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv"

if not os.path.exists(metadata_path):
    raise FileNotFoundError(
        f"JSRT metadata not found:\n{metadata_path}"
    )

jsrt = pd.read_csv(metadata_path)

print("\nLoaded:")
print(metadata_path)

print("\nOriginal shape:")
print(jsrt.shape)

print("\nColumns:")
print(jsrt.columns.tolist())


# ------------------------------------------------
# 2. Construct proper cancer target
# ------------------------------------------------

# Only malignant and benign cases are suitable for
# supervised lung-cancer classification.
#
# malignant -> 1
# benign    -> 0
# non-nodule -> excluded

jsrt_cancer = jsrt[
    jsrt["state"].isin(["malignant", "benign"])
].copy()

jsrt_cancer["lung_cancer"] = (
    jsrt_cancer["state"]
    .map({
        "malignant": 1,
        "benign": 0
    })
    .astype(int)
)


# ------------------------------------------------
# 3. Remove records without a valid diagnosis
# ------------------------------------------------

jsrt_cancer = jsrt_cancer[
    jsrt_cancer["diagnosis"].notna()
].copy()


# ------------------------------------------------
# 4. Validate target
# ------------------------------------------------

print("\n" + "=" * 70)
print("CLEAN CANCER-LABELED JSRT DATASET")
print("=" * 70)

print("\nRecords:")
print(len(jsrt_cancer))

print("\nTarget distribution:")

target_counts = jsrt_cancer["lung_cancer"].value_counts().sort_index()

for target, count in target_counts.items():

    label = "Non-cancer / Benign" if target == 0 else "Lung cancer / Malignant"

    percentage = count / len(jsrt_cancer) * 100

    print(
        f"{label:<25}: {count:4d} "
        f"({percentage:6.2f}%)"
    )


# ------------------------------------------------
# 5. Verify no non-nodule cases remain
# ------------------------------------------------

print("\nState distribution:")
print(jsrt_cancer["state"].value_counts())

assert "non-nodule" not in jsrt_cancer["state"].values

print("\n✓ Non-nodule records excluded")


# ------------------------------------------------
# 6. Check missing values
# ------------------------------------------------

print("\nMissing values:")

missing = jsrt_cancer.isna().sum()

print(missing[missing > 0])

# Some variables such as subtlety, size, x, y may still
# be missing in other JSRT records, so report them rather
# than silently filling them.

print("\n")


# ------------------------------------------------
# 7. Search for actual JSRT image files
# ------------------------------------------------

print("=" * 70)
print("SEARCHING FOR JSRT IMAGE FILES")
print("=" * 70)

search_roots = [
    "/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt",
    "/kaggle/input",
    "/kaggle/working"
]

image_extensions = [
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.bmp",
    "*.tif",
    "*.tiff"
]

image_files = []

for root in search_roots:

    if not os.path.exists(root):
        continue

    for ext in image_extensions:

        image_files.extend(
            glob.glob(
                os.path.join(root, "**", ext),
                recursive=True
            )
        )

# Remove duplicates
image_files = sorted(set(image_files))

print("\nTotal image files discovered:")
print(len(image_files))


# ------------------------------------------------
# 8. Identify JSRT images by study ID
# ------------------------------------------------

image_map = {}

for path in image_files:

    filename = os.path.basename(path)

    # JSRT study IDs look like:
    # JPCLN001.png
    # JPCLN002.png
    # etc.

    if filename.startswith("JPCLN"):

        image_map[filename] = path


print("\nJSRT images identified:")
print(len(image_map))


# ------------------------------------------------
# 9. Match metadata records to image files
# ------------------------------------------------

jsrt_cancer["image_path"] = jsrt_cancer["study_id"].map(image_map)

matched = jsrt_cancer["image_path"].notna().sum()
unmatched = jsrt_cancer["image_path"].isna().sum()

print("\n" + "=" * 70)
print("JSRT IMAGE-METADATA MATCHING")
print("=" * 70)

print(f"\nCancer-labeled records : {len(jsrt_cancer)}")
print(f"Images matched         : {matched}")
print(f"Images not found       : {unmatched}")


# ------------------------------------------------
# 10. Display unmatched records if any
# ------------------------------------------------

if unmatched > 0:

    print("\nUnmatched study IDs:")

    print(
        jsrt_cancer.loc[
            jsrt_cancer["image_path"].isna(),
            ["study_id", "state", "diagnosis"]
        ].to_string(index=False)
    )

else:

    print("\n✓ Every cancer-labeled JSRT record has an image")


# ------------------------------------------------
# 11. Keep only records with actual images
# ------------------------------------------------

jsrt_cancer_images = jsrt_cancer[
    jsrt_cancer["image_path"].notna()
].copy()

print("\nFinal image-based cancer dataset:")
print(jsrt_cancer_images.shape)


# ------------------------------------------------
# 12. Final validation
# ------------------------------------------------

assert jsrt_cancer_images["study_id"].is_unique
assert jsrt_cancer_images["lung_cancer"].isin([0, 1]).all()

print("\n" + "=" * 70)
print("FINAL VALIDATION")
print("=" * 70)

print("\nUnique study IDs:")
print(jsrt_cancer_images["study_id"].nunique())

print("\nFinal target distribution:")
print(
    jsrt_cancer_images["lung_cancer"]
    .value_counts()
    .sort_index()
)

print("\nFinal states:")
print(
    jsrt_cancer_images["state"]
    .value_counts()
)

print("\n✓ One row per JSRT image")
print("✓ Only benign and malignant cases retained")
print("✓ Non-nodule cases excluded")
print("✓ Cancer target = malignant vs benign")
print("✓ Image paths verified")


# ------------------------------------------------
# 13. Save clean dataset
# ------------------------------------------------

output_path = "/kaggle/working/conan_jsrt_cancer_images.csv"

jsrt_cancer_images.to_csv(
    output_path,
    index=False
)

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(output_path)
print(f"Shape: {jsrt_cancer_images.shape}")

print("\nFirst 5 records:")

display(
    jsrt_cancer_images[
        [
            "study_id",
            "state",
            "diagnosis",
            "lung_cancer",
            "image_path"
        ]
    ].head()
)

======================================================================
CONAN — JSRT CANCER DATASET PREPARATION
======================================================================

Loaded:
/kaggle/input/datasets/raddar/nodules-in-chest-xrays-jsrt/jsrt_metadata.csv

Original shape:
(247, 10)

Columns:
['study_id', 'subtlety', 'size', 'age', 'gender', 'x', 'y', 'state', 'position', 'diagnosis']

======================================================================
CLEAN CANCER-LABELED JSRT DATASET
======================================================================

Records:
154

Target distribution:
Non-cancer / Benign      :   54 ( 35.06%)
Lung cancer / Malignant  :  100 ( 64.94%)

State distribution:
state
malignant    100
benign        54
Name: count, dtype: int64

✓ Non-nodule records excluded

Missing values:
Series([], dtype: int64)


======================================================================
SEARCHING FOR JSRT IMAGE FILES
======================================================================

Total image files discovered:
247

JSRT images identified:
154

======================================================================
JSRT IMAGE-METADATA MATCHING
======================================================================

Cancer-labeled records : 154
Images matched         : 154
Images not found       : 0

✓ Every cancer-labeled JSRT record has an image

Final image-based cancer dataset:
(154, 12)

======================================================================
FINAL VALIDATION
======================================================================

Unique study IDs:
154

Final target distribution:
lung_cancer
0     54
1    100
Name: count, dtype: int64

Final states:
state
malignant    100
benign        54
Name: count, dtype: int64

✓ One row per JSRT image
✓ Only benign and malignant cases retained
✓ Non-nodule cases excluded
✓ Cancer target = malignant vs benign
✓ Image paths verified

======================================================================
SAVED
======================================================================
/kaggle/working/conan_jsrt_cancer_images.csv
Shape: (154, 12)

First 5 records:

,study_id,state,diagnosis,lung_cancer,image_path
0,JPCLN001.png,malignant,lung cancer,1,/kaggle/input/datasets/raddar/nodules-in-chest...
1,JPCLN002.png,benign,pulmonary hematoma,0,/kaggle/input/datasets/raddar/nodules-in-chest...
2,JPCLN003.png,malignant,lung cancer,1,/kaggle/input/datasets/raddar/nodules-in-chest...
3,JPCLN004.png,benign,Inflammatory mass,0,/kaggle/input/datasets/raddar/nodules-in-chest...
4,JPCLN005.png,malignant,lung cancer,1,/kaggle/input/datasets/raddar/nodules-in-chest...

In [55]:
# ================================================================
# CONAN — JSRT STRATIFIED 5-FOLD CROSS-VALIDATION SETUP
# ================================================================

import pandas as pd
import numpy as np

from sklearn.model_selection import StratifiedKFold

print("=" * 70)
print("CONAN — JSRT 5-FOLD CROSS-VALIDATION")
print("=" * 70)

# ------------------------------------------------
# 1. Load cleaned JSRT dataset
# ------------------------------------------------

input_path = "/kaggle/working/conan_jsrt_cancer_images.csv"

df = pd.read_csv(input_path)

print("\nLoaded:")
print(input_path)

print("\nDataset shape:")
print(df.shape)


# ------------------------------------------------
# 2. Validate target
# ------------------------------------------------

assert "lung_cancer" in df.columns
assert "image_path" in df.columns

print("\nTarget distribution:")
print(df["lung_cancer"].value_counts().sort_index())


# ------------------------------------------------
# 3. Create stratified 5-fold split
# ------------------------------------------------

skf = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

df["fold"] = -1

for fold, (train_idx, val_idx) in enumerate(
    skf.split(df, df["lung_cancer"])
):

    df.loc[val_idx, "fold"] = fold


# ------------------------------------------------
# 4. Validate folds
# ------------------------------------------------

print("\n" + "=" * 70)
print("FOLD DISTRIBUTION")
print("=" * 70)

for fold in range(5):

    fold_data = df[df["fold"] == fold]

    malignant = int(
        (fold_data["lung_cancer"] == 1).sum()
    )

    benign = int(
        (fold_data["lung_cancer"] == 0).sum()
    )

    print(
        f"Fold {fold}: "
        f"{len(fold_data):3d} images | "
        f"Benign = {benign:2d} | "
        f"Malignant = {malignant:2d}"
    )


# ------------------------------------------------
# 5. Check every image belongs to exactly one fold
# ------------------------------------------------

assert df["fold"].isin(range(5)).all()
assert df["study_id"].is_unique
assert df["image_path"].notna().all()

print("\n✓ Every image has exactly one fold")
print("✓ No duplicate study IDs")
print("✓ All image paths exist in the dataset")


# ------------------------------------------------
# 6. Check class balance
# ------------------------------------------------

print("\n" + "=" * 70)
print("CLASS DISTRIBUTION BY FOLD")
print("=" * 70)

fold_table = pd.crosstab(
    df["fold"],
    df["lung_cancer"]
)

fold_table.columns = [
    "Benign" if c == 0 else "Malignant"
    for c in fold_table.columns
]

print(fold_table)


# ------------------------------------------------
# 7. Save
# ------------------------------------------------

output_path = "/kaggle/working/conan_jsrt_5fold.csv"

df.to_csv(
    output_path,
    index=False
)

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(output_path)
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

======================================================================
CONAN — JSRT 5-FOLD CROSS-VALIDATION
======================================================================

Loaded:
/kaggle/working/conan_jsrt_cancer_images.csv

Dataset shape:
(154, 12)

Target distribution:
lung_cancer
0     54
1    100
Name: count, dtype: int64

======================================================================
FOLD DISTRIBUTION
======================================================================
Fold 0:  31 images | Benign = 11 | Malignant = 20
Fold 1:  31 images | Benign = 11 | Malignant = 20
Fold 2:  31 images | Benign = 11 | Malignant = 20
Fold 3:  31 images | Benign = 11 | Malignant = 20
Fold 4:  30 images | Benign = 10 | Malignant = 20

✓ Every image has exactly one fold
✓ No duplicate study IDs
✓ All image paths exist in the dataset

======================================================================
CLASS DISTRIBUTION BY FOLD
======================================================================
      Benign  Malignant
fold
0         11         20
1         11         20
2         11         20
3         11         20
4         10         20

======================================================================
SAVED
======================================================================
/kaggle/working/conan_jsrt_5fold.csv
Shape: (154, 13)

Columns:
['study_id', 'subtlety', 'size', 'age', 'gender', 'x', 'y', 'state', 'position', 'diagnosis', 'lung_cancer', 'image_path', 'fold']

In [ ]:
# ================================================================
# CONAN — JSRT IMAGE PREPROCESSING + RESNET-50 FEATURE EXTRACTION
# ================================================================

import os
import numpy as np
import pandas as pd
from PIL import Image

import torch
import torchvision
from torchvision import models, transforms

print("=" * 70)
print("CONAN — JSRT CNN FEATURE EXTRACTION")
print("=" * 70)

# ------------------------------------------------
# 1. Load the 5-fold dataset
# ------------------------------------------------

input_path = "/kaggle/working/conan_jsrt_5fold.csv"

df = pd.read_csv(input_path)

print("\nLoaded:")
print(input_path)

print("\nDataset:")
print(df.shape)


# ------------------------------------------------
# 2. Select device
# ------------------------------------------------

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("\nDevice:")
print(device)

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))


# ------------------------------------------------
# 3. Load pretrained ResNet-50
# ------------------------------------------------

print("\nLoading pretrained ResNet-50...")

weights = models.ResNet50_Weights.DEFAULT

resnet = models.resnet50(
    weights=weights
)

# Remove final classification layer.
# Output becomes the 2048-dimensional image embedding.

feature_extractor = torch.nn.Sequential(
    *list(resnet.children())[:-1]
)

feature_extractor = feature_extractor.to(device)
feature_extractor.eval()

print("✓ ResNet-50 loaded")
print("✓ Classification layer removed")
print("Embedding size: 2048")


# ------------------------------------------------
# 4. Image preprocessing
# ------------------------------------------------

preprocess = transforms.Compose([
    transforms.Resize((224, 224)),

    transforms.Grayscale(num_output_channels=3),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])


# ------------------------------------------------
# 5. Verify image paths
# ------------------------------------------------

missing_images = []

for path in df["image_path"]:

    if not os.path.exists(path):
        missing_images.append(path)

print("\nImage verification:")

print("Total images:", len(df))
print("Missing images:", len(missing_images))

if missing_images:

    print("\nFirst missing files:")
    print(missing_images[:10])

    raise FileNotFoundError(
        "Some JSRT images cannot be found."
    )

print("✓ All JSRT images found")


# ------------------------------------------------
# 6. Extract CNN embeddings
# ------------------------------------------------

print("\n" + "=" * 70)
print("EXTRACTING CNN EMBEDDINGS")
print("=" * 70)

embeddings = []

with torch.no_grad():

    for i, path in enumerate(df["image_path"]):

        try:

            image = Image.open(path).convert("L")

            image_tensor = preprocess(
                image
            ).unsqueeze(0).to(device)

            embedding = feature_extractor(
                image_tensor
            )

            embedding = embedding.squeeze()

            embedding = embedding.cpu().numpy()

            embeddings.append(embedding)

        except Exception as e:

            print(
                f"\nError processing image {i}: "
                f"{path}"
            )

            print(e)

            raise

        if (i + 1) % 10 == 0:

            print(
                f"Processed "
                f"{i + 1}/{len(df)}"
            )


# ------------------------------------------------
# 7. Convert to matrix
# ------------------------------------------------

X_cnn = np.vstack(embeddings)

print("\n" + "=" * 70)
print("CNN EMBEDDING MATRIX")
print("=" * 70)

print("\nShape:")
print(X_cnn.shape)

print("\nExpected:")
print("(154, 2048)")

assert X_cnn.shape == (len(df), 2048)

print("\n✓ Correct embedding dimensions")


# ------------------------------------------------
# 8. Save embeddings
# ------------------------------------------------

embedding_columns = [
    f"cnn_{i:04d}"
    for i in range(X_cnn.shape[1])
]

embedding_df = pd.DataFrame(
    X_cnn,
    columns=embedding_columns
)

embedding_df.insert(
    0,
    "study_id",
    df["study_id"].values
)

embedding_df["lung_cancer"] = (
    df["lung_cancer"].values
)

embedding_df["fold"] = (
    df["fold"].values
)


output_path = (
    "/kaggle/working/"
    "conan_jsrt_resnet50_embeddings.csv"
)

embedding_df.to_csv(
    output_path,
    index=False
)


# ------------------------------------------------
# 9. Final output
# ------------------------------------------------

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(output_path)

print("\nShape:")
print(embedding_df.shape)

print("\nColumns:")
print(
    f"study_id + "
    f"{len(embedding_columns)} CNN features + "
    f"lung_cancer + fold"
)

print("\n✓ CNN feature extraction complete")

======================================================================
CONAN — JSRT CNN FEATURE EXTRACTION
======================================================================

Loaded:
/kaggle/working/conan_jsrt_5fold.csv

Dataset:
(154, 13)

Device:
cpu

Loading pretrained ResNet-50...
Downloading: "https://download.pytorch.org/models/resnet50-11ad3fa6.pth" to /root/.cache/torch/hub/checkpoints/resnet50-11ad3fa6.pth

100%|██████████| 97.8M/97.8M [00:00<00:00, 111MB/s]

✓ ResNet-50 loaded
✓ Classification layer removed
Embedding size: 2048

Image verification:
Total images: 154
Missing images: 0
✓ All JSRT images found

======================================================================
EXTRACTING CNN EMBEDDINGS
======================================================================
Processed 10/154
Processed 20/154
Processed 30/154
Processed 40/154
Processed 50/154
Processed 60/154
Processed 70/154
Processed 80/154
Processed 90/154

In [57]:
# ================================================================
# CONAN — CNN EMBEDDING 5-FOLD OOF CANCER RISK MODEL
# ================================================================

import os
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

print("=" * 70)
print("CONAN — CNN EMBEDDING 5-FOLD OOF CANCER RISK MODEL")
print("=" * 70)

# ------------------------------------------------
# 1. LOAD CNN EMBEDDINGS
# ------------------------------------------------

path = "/kaggle/working/conan_jsrt_resnet50_embeddings.csv"

if not os.path.exists(path):
    raise FileNotFoundError(
        f"Could not find:\n{path}"
    )

df = pd.read_csv(path)

print("\nLoaded:")
print(path)

print("\nDataset shape:")
print(df.shape)

# ------------------------------------------------
# 2. IDENTIFY CNN FEATURES
# ------------------------------------------------

excluded = [
    "study_id",
    "lung_cancer",
    "fold"
]

feature_cols = [
    c for c in df.columns
    if c not in excluded
]

print("\nCNN feature count:")
print(len(feature_cols))

if len(feature_cols) != 2048:
    raise ValueError(
        f"Expected 2048 CNN features, found {len(feature_cols)}"
    )

X = df[feature_cols].astype(np.float32).values
y = df["lung_cancer"].astype(int).values
folds = df["fold"].astype(int).values

print("\nFeature matrix:")
print(X.shape)

print("\nTarget distribution:")
print(pd.Series(y).value_counts().sort_index())

print("\nFold distribution:")
print(
    pd.DataFrame({
        "fold": folds,
        "lung_cancer": y
    })
    .groupby(["fold", "lung_cancer"])
    .size()
    .unstack(fill_value=0)
)

# ------------------------------------------------
# 3. OOF PREDICTIONS
# ------------------------------------------------

oof_pred = np.zeros(len(df), dtype=float)
oof_class = np.zeros(len(df), dtype=int)

fold_results = []

print("\n" + "=" * 70)
print("TRAINING 5 FOLDS")
print("=" * 70)

for fold in sorted(np.unique(folds)):

    train_idx = folds != fold
    test_idx = folds == fold

    X_train = X[train_idx]
    X_test = X[test_idx]

    y_train = y[train_idx]
    y_test = y[test_idx]

    print(f"\nFold {fold}")
    print("-" * 50)
    print(f"Training images : {len(X_train)}")
    print(f"Validation images: {len(X_test)}")
    print(
        f"Train cancer    : {y_train.sum()} / {len(y_train)}"
    )
    print(
        f"Valid cancer    : {y_test.sum()} / {len(y_test)}"
    )

    # ------------------------------------------------
    # IMPORTANT:
    # Scaling is fitted ONLY on training data.
    # ------------------------------------------------

    model = Pipeline([
        (
            "scaler",
            StandardScaler()
        ),
        (
            "classifier",
            LogisticRegression(
                C=0.03,
                max_iter=3000,
                class_weight="balanced",
                solver="liblinear",
                random_state=42
            )
        )
    ])

    model.fit(X_train, y_train)

    prob = model.predict_proba(X_test)[:, 1]
    pred = (prob >= 0.5).astype(int)

    oof_pred[test_idx] = prob
    oof_class[test_idx] = pred

    fold_auc = roc_auc_score(y_test, prob)

    fold_results.append({
        "fold": fold,
        "n": len(y_test),
        "benign": int((y_test == 0).sum()),
        "malignant": int((y_test == 1).sum()),
        "roc_auc": fold_auc
    })

    print(f"Fold ROC-AUC: {fold_auc:.4f}")

# ------------------------------------------------
# 4. OVERALL OOF PERFORMANCE
# ------------------------------------------------

print("\n" + "=" * 70)
print("OVERALL 5-FOLD OOF PERFORMANCE")
print("=" * 70)

auc = roc_auc_score(y, oof_pred)
accuracy = accuracy_score(y, oof_class)
balanced_acc = balanced_accuracy_score(y, oof_class)
precision = precision_score(y, oof_class, zero_division=0)
recall = recall_score(y, oof_class, zero_division=0)
f1 = f1_score(y, oof_class, zero_division=0)

print(f"\nROC-AUC            : {auc:.4f}")
print(f"Accuracy           : {accuracy:.4f}")
print(f"Balanced Accuracy  : {balanced_acc:.4f}")
print(f"Precision          : {precision:.4f}")
print(f"Recall             : {recall:.4f}")
print(f"F1 Score           : {f1:.4f}")

# ------------------------------------------------
# 5. CONFUSION MATRIX
# ------------------------------------------------

cm = confusion_matrix(y, oof_class)

print("\nConfusion Matrix:")
print(cm)

# ------------------------------------------------
# 6. FOLD SUMMARY
# ------------------------------------------------

fold_df = pd.DataFrame(fold_results)

print("\nFold Results:")
print(fold_df.to_string(index=False))

print("\nFold ROC-AUC mean:")
print(f"{fold_df['roc_auc'].mean():.4f}")

print("\nFold ROC-AUC standard deviation:")
print(f"{fold_df['roc_auc'].std():.4f}")

# ------------------------------------------------
# 7. SAVE OOF PREDICTIONS
# ------------------------------------------------

oof_df = df[
    ["study_id", "lung_cancer", "fold"]
].copy()

oof_df["cnn_risk_probability"] = oof_pred
oof_df["cnn_prediction"] = oof_class

output_path = "/kaggle/working/conan_jsrt_cnn_oof_predictions.csv"

oof_df.to_csv(output_path, index=False)

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(output_path)
print("Shape:", oof_df.shape)

print("\n✓ Every image has an out-of-fold CNN prediction")
print("✓ No validation image was used to train its fold model")
print("✓ CNN risk probability generated")

======================================================================
CONAN — CNN EMBEDDING 5-FOLD OOF CANCER RISK MODEL
======================================================================

Loaded:
/kaggle/working/conan_jsrt_resnet50_embeddings.csv

Dataset shape:
(154, 2051)

CNN feature count:
2048

Feature matrix:
(154, 2048)

Target distribution:
0     54
1    100
Name: count, dtype: int64

Fold distribution:
lung_cancer   0   1
fold
0            11  20
1            11  20
2            11  20
3            11  20
4            10  20

======================================================================
TRAINING 5 FOLDS
======================================================================

Fold 0
--------------------------------------------------
Training images : 123
Validation images: 31
Train cancer    : 80 / 123
Valid cancer    : 20 / 31
Fold ROC-AUC: 0.4727

Fold 1
--------------------------------------------------
Training images : 123
Validation images: 31
Train cancer    : 80 / 123
Valid cancer    : 20 / 31
Fold ROC-AUC: 0.6636

Fold 2
--------------------------------------------------
Training images : 123
Validation images: 31
Train cancer    : 80 / 123
Valid cancer    : 20 / 31
Fold ROC-AUC: 0.7909

Fold 3
--------------------------------------------------
Training images : 123
Validation images: 31
Train cancer    : 80 / 123
Valid cancer    : 20 / 31
Fold ROC-AUC: 0.5227

Fold 4
--------------------------------------------------
Training images : 124
Validation images: 30
Train cancer    : 80 / 124
Valid cancer    : 20 / 30
Fold ROC-AUC: 0.7250

======================================================================
OVERALL 5-FOLD OOF PERFORMANCE
======================================================================

ROC-AUC            : 0.6274
Accuracy           : 0.6039
Balanced Accuracy  : 0.6183
Precision          : 0.7600
Recall             : 0.5700
F1 Score           : 0.6514

Confusion Matrix:
[[36 18]
 [43 57]]

Fold Results:
 fold  n  benign  malignant  roc_auc
    0 31      11         20 0.472727
    1 31      11         20 0.663636
    2 31      11         20 0.790909
    3 31      11         20 0.522727
    4 30      10         20 0.725000

Fold ROC-AUC mean:
0.6350

Fold ROC-AUC standard deviation:
0.1343

======================================================================
SAVED
======================================================================
/kaggle/working/conan_jsrt_cnn_oof_predictions.csv
Shape: (154, 5)

✓ Every image has an out-of-fold CNN prediction
✓ No validation image was used to train its fold model
✓ CNN risk probability generated

In [58]:
# ================================================================
# CONAN — JSRT RESNET-50 FINE-TUNING
# 5-FOLD OUT-OF-FOLD LUNG CANCER RISK MODEL
# ================================================================

import os
import copy
import random
import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms

from sklearn.metrics import (
    roc_auc_score,
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix
)

# ================================================================
# CONFIGURATION
# ================================================================

SEED = 42

BATCH_SIZE = 8
NUM_EPOCHS = 15
LEARNING_RATE = 1e-4
WEIGHT_DECAY = 1e-4

PATIENCE = 4

IMAGE_SIZE = 224

DEVICE = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("=" * 70)
print("CONAN — JSRT RESNET-50 FINE-TUNING")
print("=" * 70)

print("\nDevice:")
print(DEVICE)

# ------------------------------------------------
# Reproducibility
# ------------------------------------------------

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if torch.cuda.is_available():
    torch.cuda.manual_seed_all(SEED)

# ================================================================
# 1. LOAD JSRT DATA
# ================================================================

DATA_PATH = "/kaggle/working/conan_jsrt_5fold.csv"

if not os.path.exists(DATA_PATH):
    raise FileNotFoundError(
        f"Dataset not found:\n{DATA_PATH}"
    )

df = pd.read_csv(DATA_PATH)

print("\nLoaded:")
print(DATA_PATH)

print("\nDataset shape:")
print(df.shape)

required_columns = [
    "study_id",
    "lung_cancer",
    "image_path",
    "fold"
]

for col in required_columns:
    if col not in df.columns:
        raise ValueError(
            f"Required column missing: {col}"
        )

# ================================================================
# 2. VALIDATE DATA
# ================================================================

print("\n" + "=" * 70)
print("DATA VALIDATION")
print("=" * 70)

print("\nTarget distribution:")
print(df["lung_cancer"].value_counts().sort_index())

print("\nFold distribution:")
print(
    df.groupby(["fold", "lung_cancer"])
      .size()
      .unstack(fill_value=0)
)

# Check duplicate studies
duplicates = df["study_id"].duplicated().sum()

print("\nDuplicate study IDs:")
print(duplicates)

if duplicates != 0:
    raise ValueError("Duplicate study IDs detected.")

# Check image paths
missing_images = [
    p for p in df["image_path"]
    if not os.path.exists(p)
]

print("\nMissing images:")
print(len(missing_images))

if len(missing_images) > 0:
    print(missing_images[:10])
    raise FileNotFoundError(
        "Some JSRT images could not be found."
    )

print("\n✓ Dataset validated")
print("✓ One row per image")
print("✓ All images exist")
print("✓ No duplicate study IDs")

# ================================================================
# 3. DATASET CLASS
# ================================================================

class JSRTDataset(Dataset):

    def __init__(self, dataframe, transform=None):

        self.df = dataframe.reset_index(drop=True)
        self.transform = transform

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):

        row = self.df.iloc[idx]

        image_path = row["image_path"]
        label = int(row["lung_cancer"])

        # ------------------------------------------------
        # JSRT X-ray
        # ------------------------------------------------

        image = Image.open(image_path).convert("RGB")

        if self.transform is not None:
            image = self.transform(image)

        return image, torch.tensor(
            label,
            dtype=torch.float32
        )

# ================================================================
# 4. IMAGE TRANSFORMS
# ================================================================

# Training augmentation
train_transform = transforms.Compose([

    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),

    transforms.RandomHorizontalFlip(
        p=0.5
    ),

    transforms.RandomRotation(
        degrees=5
    ),

    transforms.RandomAffine(
        degrees=0,
        translate=(0.03, 0.03),
        scale=(0.97, 1.03)
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

# Validation transform
val_transform = transforms.Compose([

    transforms.Resize(
        (IMAGE_SIZE, IMAGE_SIZE)
    ),

    transforms.ToTensor(),

    transforms.Normalize(
        mean=[0.485, 0.456, 0.406],
        std=[0.229, 0.224, 0.225]
    )
])

print("\n✓ Training augmentation configured")
print("✓ Validation transformation configured")

# ================================================================
# 5. RESNET-50 MODEL
# ================================================================

def create_model():

    print("\nLoading pretrained ResNet-50...")

    model = models.resnet50(
        weights=models.ResNet50_Weights.DEFAULT
    )

    # ------------------------------------------------
    # Freeze entire network initially
    # ------------------------------------------------

    for param in model.parameters():
        param.requires_grad = False

    # ------------------------------------------------
    # Fine-tune final convolutional block
    # ------------------------------------------------

    for param in model.layer4.parameters():
        param.requires_grad = True

    # ------------------------------------------------
    # Replace classifier
    # ------------------------------------------------

    num_features = model.fc.in_features

    model.fc = nn.Sequential(

        nn.Dropout(
            p=0.40
        ),

        nn.Linear(
            num_features,
            1
        )
    )

    # New classifier must train
    for param in model.fc.parameters():
        param.requires_grad = True

    return model.to(DEVICE)

# ================================================================
# 6. TRAINING FUNCTION
# ================================================================

def train_one_fold(
    train_df,
    val_df,
    fold_number
):

    print("\n" + "=" * 70)
    print(f"TRAINING FOLD {fold_number}")
    print("=" * 70)

    print(
        f"Training images   : {len(train_df)}"
    )

    print(
        f"Validation images : {len(val_df)}"
    )

    print(
        f"Training cancer   : {train_df['lung_cancer'].sum()} / {len(train_df)}"
    )

    print(
        f"Validation cancer : {val_df['lung_cancer'].sum()} / {len(val_df)}"
    )

    # ------------------------------------------------
    # Datasets
    # ------------------------------------------------

    train_dataset = JSRTDataset(
        train_df,
        transform=train_transform
    )

    val_dataset = JSRTDataset(
        val_df,
        transform=val_transform
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        num_workers=2,
        pin_memory=torch.cuda.is_available()
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=2,
        pin_memory=torch.cuda.is_available()
    )

    # ------------------------------------------------
    # Model
    # ------------------------------------------------

    model = create_model()

    # ------------------------------------------------
    # Class weighting
    # ------------------------------------------------

    train_labels = train_df["lung_cancer"].values

    n_negative = np.sum(train_labels == 0)
    n_positive = np.sum(train_labels == 1)

    pos_weight = (
        n_negative / n_positive
    )

    pos_weight_tensor = torch.tensor(
        [pos_weight],
        dtype=torch.float32,
        device=DEVICE
    )

    criterion = nn.BCEWithLogitsLoss(
        pos_weight=pos_weight_tensor
    )

    # ------------------------------------------------
    # Optimizer
    # ------------------------------------------------

    trainable_params = [
        p for p in model.parameters()
        if p.requires_grad
    ]

    optimizer = torch.optim.AdamW(
        trainable_params,
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY
    )

    scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
        optimizer,
        mode="max",
        factor=0.5,
        patience=2
    )

    # ------------------------------------------------
    # Early stopping
    # ------------------------------------------------

    best_auc = -np.inf
    best_state = None
    patience_counter = 0

    # ====================================================
    # EPOCH LOOP
    # ====================================================

    for epoch in range(NUM_EPOCHS):

        # ------------------------------------------------
        # TRAIN
        # ------------------------------------------------

        model.train()

        train_loss = 0.0

        for images, labels in train_loader:

            images = images.to(
                DEVICE,
                non_blocking=True
            )

            labels = labels.to(
                DEVICE,
                non_blocking=True
            ).unsqueeze(1)

            optimizer.zero_grad()

            logits = model(images)

            loss = criterion(
                logits,
                labels
            )

            loss.backward()

            optimizer.step()

            train_loss += (
                loss.item() * images.size(0)
            )

        train_loss /= len(train_dataset)

        # ------------------------------------------------
        # VALIDATION
        # ------------------------------------------------

        model.eval()

        val_probs = []
        val_labels = []

        with torch.no_grad():

            for images, labels in val_loader:

                images = images.to(
                    DEVICE,
                    non_blocking=True
                )

                logits = model(images)

                probs = torch.sigmoid(
                    logits
                ).flatten()

                val_probs.extend(
                    probs.cpu().numpy()
                )

                val_labels.extend(
                    labels.numpy()
                )

        val_probs = np.asarray(
            val_probs
        )

        val_labels = np.asarray(
            val_labels
        ).astype(int)

        val_auc = roc_auc_score(
            val_labels,
            val_probs
        )

        scheduler.step(val_auc)

        print(
            f"Epoch {epoch + 1:02d}/{NUM_EPOCHS} | "
            f"Loss: {train_loss:.4f} | "
            f"Val AUC: {val_auc:.4f}"
        )

        # ------------------------------------------------
        # Save best model
        # ------------------------------------------------

        if val_auc > best_auc:

            best_auc = val_auc

            best_state = copy.deepcopy(
                model.state_dict()
            )

            patience_counter = 0

        else:

            patience_counter += 1

        if patience_counter >= PATIENCE:

            print(
                f"Early stopping at epoch "
                f"{epoch + 1}"
            )

            break

    # ====================================================
    # RESTORE BEST MODEL
    # ====================================================

    if best_state is not None:

        model.load_state_dict(
            best_state
        )

    print(
        f"\nBest validation ROC-AUC: "
        f"{best_auc:.4f}"
    )

    # ====================================================
    # FINAL VALIDATION PREDICTIONS
    # ====================================================

    model.eval()

    final_probs = []

    with torch.no_grad():

        for images, labels in val_loader:

            images = images.to(
                DEVICE,
                non_blocking=True
            )

            logits = model(images)

            probs = torch.sigmoid(
                logits
            ).flatten()

            final_probs.extend(
                probs.cpu().numpy()
            )

    final_probs = np.asarray(
        final_probs
    )

    return final_probs, best_auc

# ================================================================
# 7. 5-FOLD OUT-OF-FOLD TRAINING
# ================================================================

print("\n" + "=" * 70)
print("5-FOLD OUT-OF-FOLD FINE-TUNING")
print("=" * 70)

oof_predictions = np.zeros(
    len(df),
    dtype=float
)

fold_results = []

unique_folds = sorted(
    df["fold"].unique()
)

for fold in unique_folds:

    train_df = df[
        df["fold"] != fold
    ].copy()

    val_df = df[
        df["fold"] == fold
    ].copy()

    val_probs, best_auc = train_one_fold(
        train_df,
        val_df,
        fold
    )

    # Put predictions back into original rows
    val_indices = val_df.index.values

    oof_predictions[
        val_indices
    ] = val_probs

    fold_results.append({

        "fold": int(fold),

        "n": len(val_df),

        "benign": int(
            (val_df["lung_cancer"] == 0).sum()
        ),

        "malignant": int(
            (val_df["lung_cancer"] == 1).sum()
        ),

        "roc_auc": best_auc
    })

# ================================================================
# 8. OVERALL OOF PERFORMANCE
# ================================================================

y_true = df[
    "lung_cancer"
].astype(int).values

oof_classes = (
    oof_predictions >= 0.5
).astype(int)

overall_auc = roc_auc_score(
    y_true,
    oof_predictions
)

accuracy = accuracy_score(
    y_true,
    oof_classes
)

balanced_accuracy = balanced_accuracy_score(
    y_true,
    oof_classes
)

precision = precision_score(
    y_true,
    oof_classes,
    zero_division=0
)

recall = recall_score(
    y_true,
    oof_classes,
    zero_division=0
)

f1 = f1_score(
    y_true,
    oof_classes,
    zero_division=0
)

cm = confusion_matrix(
    y_true,
    oof_classes
)

# ================================================================
# 9. RESULTS
# ================================================================

fold_df = pd.DataFrame(
    fold_results
)

print("\n" + "=" * 70)
print("FINAL 5-FOLD OOF RESULTS")
print("=" * 70)

print(
    f"\nOverall OOF ROC-AUC   : "
    f"{overall_auc:.4f}"
)

print(
    f"Accuracy              : "
    f"{accuracy:.4f}"
)

print(
    f"Balanced Accuracy     : "
    f"{balanced_accuracy:.4f}"
)

print(
    f"Precision             : "
    f"{precision:.4f}"
)

print(
    f"Recall                : "
    f"{recall:.4f}"
)

print(
    f"F1 Score              : "
    f"{f1:.4f}"
)

print("\nConfusion Matrix:")
print(cm)

print("\nFold Results:")
print(
    fold_df.to_string(
        index=False
    )
)

print(
    "\nMean Fold ROC-AUC: "
    f"{fold_df['roc_auc'].mean():.4f}"
)

print(
    "Fold ROC-AUC SD: "
    f"{fold_df['roc_auc'].std():.4f}"
)

# ================================================================
# 10. SAVE OOF PREDICTIONS
# ================================================================

output = df[
    [
        "study_id",
        "lung_cancer",
        "fold"
    ]
].copy()

output[
    "cnn_finetuned_risk_probability"
] = oof_predictions

output[
    "cnn_finetuned_prediction"
] = oof_classes

output_path = (
    "/kaggle/working/"
    "conan_jsrt_resnet50_finetuned_oof.csv"
)

output.to_csv(
    output_path,
    index=False
)

print("\n" + "=" * 70)
print("SAVED")
print("=" * 70)

print(output_path)
print("Shape:", output.shape)

print("\n✓ 5-fold OOF predictions generated")
print("✓ Validation images were not used for training")
print("✓ ResNet-50 layer4 was fine-tuned")
print("✓ Cancer probabilities generated")
print("✓ Results are ready for comparison")

======================================================================
CONAN — JSRT RESNET-50 FINE-TUNING
======================================================================

Device:
cpu

Loaded:
/kaggle/working/conan_jsrt_5fold.csv

Dataset shape:
(154, 13)

======================================================================
DATA VALIDATION
======================================================================

Target distribution:
lung_cancer
0     54
1    100
Name: count, dtype: int64

Fold distribution:
lung_cancer   0   1
fold
0            11  20
1            11  20
2            11  20
3            11  20
4            10  20

Duplicate study IDs:
0

Missing images:
0

✓ Dataset validated
✓ One row per image
✓ All images exist
✓ No duplicate study IDs

✓ Training augmentation configured
✓ Validation transformation configured

======================================================================
5-FOLD OUT-OF-FOLD FINE-TUNING
======================================================================

======================================================================
TRAINING FOLD 0
======================================================================
Training images   : 123
Validation images : 31
Training cancer   : 80 / 123
Validation cancer : 20 / 31

Loading pretrained ResNet-50...
Epoch 01/15 | Loss: 0.4817 | Val AUC: 0.5818
Epoch 02/15 | Loss: 0.4804 | Val AUC: 0.5364
Epoch 03/15 | Loss: 0.4662 | Val AUC: 0.5773
Epoch 04/15 | Loss: 0.4596 | Val AUC: 0.4727
Epoch 05/15 | Loss: 0.4488 | Val AUC: 0.5591
Early stopping at epoch 5

Best validation ROC-AUC: 0.5818

======================================================================
TRAINING FOLD 1
======================================================================
Training images   : 123
Validation images : 31
Training cancer   : 80 / 123
Validation cancer : 20 / 31

Loading pretrained ResNet-50...
Epoch 01/15 | Loss: 0.4872 | Val AUC: 0.6182
Epoch 02/15 | Loss: 0.4783 | Val AUC: 0.6727
Epoch 03/15 | Loss: 0.4681 | Val AUC: 0.6727
Epoch 04/15 | Loss: 0.4712 | Val AUC: 0.6773
Epoch 05/15 | Loss: 0.4539 | Val AUC: 0.6864
Epoch 06/15 | Loss: 0.4361 | Val AUC: 0.7273
Epoch 07/15 | Loss: 0.4188 | Val AUC: 0.7000
Epoch 08/15 | Loss: 0.4044 | Val AUC: 0.6909
Epoch 09/15 | Loss: 0.3741 | Val AUC: 0.6773
Epoch 10/15 | Loss: 0.3329 | Val AUC: 0.6682
Early stopping at epoch 10

Best validation ROC-AUC: 0.7273

======================================================================
TRAINING FOLD 2
======================================================================
Training images   : 123
Validation images : 31
Training cancer   : 80 / 123
Validation cancer : 20 / 31

Loading pretrained ResNet-50...
Epoch 01/15 | Loss: 0.4840 | Val AUC: 0.5773
Epoch 02/15 | Loss: 0.4737 | Val AUC: 0.7091
Epoch 03/15 | Loss: 0.4746 | Val AUC: 0.5591
Epoch 04/15 | Loss: 0.4552 | Val AUC: 0.6000
Epoch 05/15 | Loss: 0.4507 | Val AUC: 0.7455
Epoch 06/15 | Loss: 0.4289 | Val AUC: 0.6818
Epoch 07/15 | Loss: 0.4069 | Val AUC: 0.6409
Epoch 08/15 | Loss: 0.3986 | Val AUC: 0.6409
Epoch 09/15 | Loss: 0.3909 | Val AUC: 0.6364
Early stopping at epoch 9

Best validation ROC-AUC: 0.7455

======================================================================
TRAINING FOLD 3
======================================================================
Training images   : 123
Validation images : 31
Training cancer   : 80 / 123
Validation cancer : 20 / 31

Loading pretrained ResNet-50...
Epoch 01/15 | Loss: 0.4896 | Val AUC: 0.3091
Epoch 02/15 | Loss: 0.4803 | Val AUC: 0.3773
Epoch 03/15 | Loss: 0.4717 | Val AUC: 0.6045
Epoch 04/15 | Loss: 0.4665 | Val AUC: 0.5773
Epoch 05/15 | Loss: 0.4559 | Val AUC: 0.5636
Epoch 06/15 | Loss: 0.4439 | Val AUC: 0.5955
Epoch 07/15 | Loss: 0.4345 | Val AUC: 0.6136
Epoch 08/15 | Loss: 0.4352 | Val AUC: 0.6591
Epoch 09/15 | Loss: 0.4214 | Val AUC: 0.6500
Epoch 10/15 | Loss: 0.3964 | Val AUC: 0.6545
Epoch 11/15 | Loss: 0.3770 | Val AUC: 0.6864
Epoch 12/15 | Loss: 0.3469 | Val AUC: 0.7000
Epoch 13/15 | Loss: 0.3283 | Val AUC: 0.7136
Epoch 14/15 | Loss: 0.3173 | Val AUC: 0.7318
Epoch 15/15 | Loss: 0.2874 | Val AUC: 0.7091

Best validation ROC-AUC: 0.7318

======================================================================
TRAINING FOLD 4
======================================================================
Training images   : 124
Validation images : 30
Training cancer   : 80 / 124
Validation cancer : 20 / 30

Loading pretrained ResNet-50...
Epoch 01/15 | Loss: 0.5043 | Val AUC: 0.5000
Epoch 02/15 | Loss: 0.4912 | Val AUC: 0.3950
Epoch 03/15 | Loss: 0.4799 | Val AUC: 0.5400
Epoch 04/15 | Loss: 0.4694 | Val AUC: 0.5800
Epoch 05/15 | Loss: 0.4650 | Val AUC: 0.6050
Epoch 06/15 | Loss: 0.4481 | Val AUC: 0.7400
Epoch 07/15 | Loss: 0.4446 | Val AUC: 0.8000
Epoch 08/15 | Loss: 0.3944 | Val AUC: 0.7800
Epoch 09/15 | Loss: 0.3672 | Val AUC: 0.8150
Epoch 10/15 | Loss: 0.3613 | Val AUC: 0.7550
Epoch 11/15 | Loss: 0.2975 | Val AUC: 0.7800
Epoch 12/15 | Loss: 0.2581 | Val AUC: 0.7500
Epoch 13/15 | Loss: 0.2449 | Val AUC: 0.7500
Early stopping at epoch 13

Best validation ROC-AUC: 0.8150

======================================================================
FINAL 5-FOLD OOF RESULTS
======================================================================

Overall OOF ROC-AUC   : 0.7020
Accuracy              : 0.6818
Balanced Accuracy     : 0.6570
Precision             : 0.7629
Recall                : 0.7400
F1 Score              : 0.7513

Confusion Matrix:
[[31 23]
 [26 74]]

Fold Results:
 fold  n  benign  malignant  roc_auc
    0 31      11         20 0.581818
    1 31      11         20 0.727273
    2 31      11         20 0.745455
    3 31      11         20 0.731818
    4 30      10         20 0.815000

Mean Fold ROC-AUC: 0.7203
Fold ROC-AUC SD: 0.0851

======================================================================
SAVED
======================================================================
/kaggle/working/conan_jsrt_resnet50_finetuned_oof.csv
Shape: (154, 5)

✓ 5-fold OOF predictions generated
✓ Validation images were not used for training
✓ ResNet-50 layer4 was fine-tuned
✓ Cancer probabilities generated
✓ Results are ready for comparison